export const ROUTES = {
  projects: '/',
  setup: '/setup',
  pipeline: '/pipeline',
  review: '/review',
  healing: '/healing',
  eject: '/eject',
  overview: '/overview',
  truthMap: '/truth-map',
  divergences: '/divergences',
  explore: '/explore',
  author: '/author',
  signals: '/signals',
  governance: '/governance',
  memory: '/memory',
  chat: '/chat',
  knowledge: '/knowledge',
  settings: '/settings',
  uiKit: '/ui-kit',
  devices: '/devices',
  sdd: '/sdd',
  sddSessions: '/sdd/sessions',
  sddExperience: '/sdd/experience',
  sddTokens: '/sdd/tokens',
  sddGraph: '/sdd/graph',
  sddWiki: '/sdd/wiki',
  sddConfig: '/sdd/config',
} as const;

export type RouteKey = keyof typeof ROUTES;
