"""
CHERENKOV cherenkov/diff/spec_differ.py — OpenAPI spec diff and breaking-change detection. Issue #437.

Detects breaking vs additive changes between two OpenAPI YAML/JSON specs.
Breaking changes cause `cherenkov diff` to exit with code 1.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

_HTTP_METHODS = {"get", "post", "put", "patch", "delete", "options", "head"}


class ChangeType(str, Enum):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    REMOVED_ENDPOINT = "removed_endpoint"
    REMOVED_REQUIRED_PARAM = "removed_required_param"
    REMOVED_RESPONSE_CODE = "removed_response_code"
    CHANGED_PARAM_TYPE = "changed_param_type"
    ADDED_ENDPOINT = "added_endpoint"
    ADDED_OPTIONAL_PARAM = "added_optional_param"
    CHANGED_DESCRIPTION = "changed_description"
    ADDED_REQUIRED_FIELD = "added_required_field"
    REMOVED_FIELD = "removed_field"
    CHANGED_FIELD_TYPE = "changed_field_type"
    REMOVED_ENUM_VALUE = "removed_enum_value"
    ADDED_ENUM_VALUE = "added_enum_value"
    REMOVED_SCHEMA = "removed_schema"
    ADDED_OPTIONAL_FIELD = "added_optional_field"


@dataclass
class SpecChange:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    change_type: ChangeType
    breaking: bool
    endpoint: str
    method: str | None
    detail: str
    before: Any = None
    after: Any = None


@dataclass
class SpecDiffReport:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    breaking: list[SpecChange] = field(default_factory=list)
    additive: list[SpecChange] = field(default_factory=list)
    informational: list[SpecChange] = field(default_factory=list)

    @property
    def has_breaking_changes(self) -> bool:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        return bool(self.breaking)

    def to_dict(self) -> dict:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        def _change_to_dict(c: SpecChange) -> dict:
            return {
                "change_type": c.change_type.value,
                "breaking": c.breaking,
                "endpoint": c.endpoint,
                "method": c.method,
                "detail": c.detail,
            }

        return {
            "breaking": [_change_to_dict(c) for c in self.breaking],
            "additive": [_change_to_dict(c) for c in self.additive],
            "informational": [_change_to_dict(c) for c in self.informational],
            "has_breaking_changes": self.has_breaking_changes,
            "summary": {
                "breaking_count": len(self.breaking),
                "additive_count": len(self.additive),
                "informational_count": len(self.informational),
            },
        }


class SpecDiffer:
    """Compare two OpenAPI specs and classify changes as breaking, additive, or informational."""

    def diff(self, before_path: str, after_path: str) -> SpecDiffReport:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        before = self._load(before_path)
        after = self._load(after_path)
        report = SpecDiffReport()

        before_paths = set(before.get("paths", {}))
        after_paths = set(after.get("paths", {}))

        # Removed endpoints — BREAKING
        for p in sorted(before_paths - after_paths):
            for method in before["paths"][p]:
                if method.lower() in _HTTP_METHODS:
                    report.breaking.append(
                        SpecChange(
                            change_type=ChangeType.REMOVED_ENDPOINT,
                            breaking=True,
                            endpoint=p,
                            method=method.upper(),
                            detail=f"Endpoint {method.upper()} {p} was removed",
                        )
                    )

        # Added endpoints — ADDITIVE
        for p in sorted(after_paths - before_paths):
            for method in after["paths"][p]:
                if method.lower() in _HTTP_METHODS:
                    report.additive.append(
                        SpecChange(
                            change_type=ChangeType.ADDED_ENDPOINT,
                            breaking=False,
                            endpoint=p,
                            method=method.upper(),
                            detail=f"New endpoint {method.upper()} {p} added",
                        )
                    )

        # Changed endpoints — inspect operations
        for p in sorted(before_paths & after_paths):
            self._diff_path_item(
                before["paths"][p],
                after["paths"][p],
                p,
                report,
                before,
                after,
            )

        self._diff_components(before, after, report)
        return report

    def _diff_path_item(
        self,
        before_item: dict,
        after_item: dict,
        path: str,
        report: SpecDiffReport,
        before_spec: dict | None = None,
        after_spec: dict | None = None,
    ) -> None:
        for method in before_item:
            if method.lower() not in _HTTP_METHODS:
                continue
            if method not in after_item:
                # Method removed — BREAKING (already caught at path level if whole path removed)
                report.breaking.append(
                    SpecChange(
                        change_type=ChangeType.REMOVED_ENDPOINT,
                        breaking=True,
                        endpoint=path,
                        method=method.upper(),
                        detail=f"HTTP method {method.upper()} removed from {path}",
                    )
                )
                continue
            before_op = before_item[method]
            after_op = after_item[method]
            self._diff_parameters(before_op, after_op, path, method, report)
            self._diff_response_codes(before_op, after_op, path, method, report)
            self._diff_bodies(
                before_op, after_op, path, method, report, before_spec or {}, after_spec or {}
            )

    def _diff_parameters(
        self,
        before_op: dict,
        after_op: dict,
        path: str,
        method: str,
        report: SpecDiffReport,
    ) -> None:
        before_params = {p["name"]: p for p in before_op.get("parameters", [])}
        after_params = {p["name"]: p for p in after_op.get("parameters", [])}

        for name, param in before_params.items():
            if name not in after_params:
                if param.get("required", False):
                    report.breaking.append(
                        SpecChange(
                            change_type=ChangeType.REMOVED_REQUIRED_PARAM,
                            breaking=True,
                            endpoint=path,
                            method=method.upper(),
                            detail=(
                                f"Required parameter '{name}' removed from "
                                f"{method.upper()} {path}"
                            ),
                        )
                    )
                else:
                    report.additive.append(
                        SpecChange(
                            change_type=ChangeType.ADDED_OPTIONAL_PARAM,
                            breaking=False,
                            endpoint=path,
                            method=method.upper(),
                            detail=f"Optional parameter '{name}' removed from {method.upper()} {path}",
                        )
                    )
            else:
                # Check type change
                before_type = param.get("schema", {}).get("type")
                after_type = after_params[name].get("schema", {}).get("type")
                if before_type and after_type and before_type != after_type:
                    report.breaking.append(
                        SpecChange(
                            change_type=ChangeType.CHANGED_PARAM_TYPE,
                            breaking=True,
                            endpoint=path,
                            method=method.upper(),
                            detail=(
                                f"Parameter '{name}' type changed from "
                                f"'{before_type}' to '{after_type}' in {method.upper()} {path}"
                            ),
                            before=before_type,
                            after=after_type,
                        )
                    )

        for name in after_params:
            if name not in before_params and after_params[name].get("required", False):
                # New required param — BREAKING (callers don't know to send it)
                report.breaking.append(
                    SpecChange(
                        change_type=ChangeType.REMOVED_REQUIRED_PARAM,
                        breaking=True,
                        endpoint=path,
                        method=method.upper(),
                        detail=(
                            f"New required parameter '{name}' added to "
                            f"{method.upper()} {path} — breaks existing callers"
                        ),
                    )
                )

    def _diff_response_codes(
        self,
        before_op: dict,
        after_op: dict,
        path: str,
        method: str,
        report: SpecDiffReport,
    ) -> None:
        before_resp = set(before_op.get("responses", {}))
        after_resp = set(after_op.get("responses", {}))

        for code in before_resp - after_resp:
            report.breaking.append(
                SpecChange(
                    change_type=ChangeType.REMOVED_RESPONSE_CODE,
                    breaking=True,
                    endpoint=path,
                    method=method.upper(),
                    detail=f"Response status {code} removed from {method.upper()} {path}",
                )
            )

    # ── schema-level changes (#995) ───────────────────────────────────────────
    # Components are compared once, by name. A body that `$ref`s the same
    # component in both specs is skipped (already covered there), so one real
    # change yields one finding. Bodies are compared only when inline or when
    # the `$ref` target changed.

    _MAX_DEPTH = 12

    def _diff_components(self, before: dict, after: dict, report: SpecDiffReport) -> None:
        b_schemas = (before.get("components") or {}).get("schemas") or {}
        a_schemas = (after.get("components") or {}).get("schemas") or {}
        for name in sorted(b_schemas):
            where = f"#/components/schemas/{name}"
            if name not in a_schemas:
                report.breaking.append(SpecChange(
                    change_type=ChangeType.REMOVED_SCHEMA, breaking=True, endpoint=where,
                    method=None, detail=f"Schema '{name}' was removed",
                ))
                continue
            self._diff_schema(b_schemas[name], a_schemas[name], where, name, None, report,
                              before, after, 0)

    def _diff_bodies(
        self,
        before_op: dict,
        after_op: dict,
        path: str,
        method: str,
        report: SpecDiffReport,
        before_spec: dict,
        after_spec: dict,
    ) -> None:
        def json_schema(content: Any) -> Any:
            media = (content or {}).get("application/json") or {}
            return media.get("schema")

        pairs = [("request body", json_schema((before_op.get("requestBody") or {}).get("content")),
                  json_schema((after_op.get("requestBody") or {}).get("content")))]
        for code, b_resp in (before_op.get("responses") or {}).items():
            a_resp = (after_op.get("responses") or {}).get(code)
            if a_resp is None:
                continue  # removal already reported by _diff_response_codes
            pairs.append((f"{code} response",
                          json_schema((b_resp or {}).get("content")),
                          json_schema((a_resp or {}).get("content"))))
        for label, b_schema, a_schema in pairs:
            if isinstance(b_schema, dict) and isinstance(a_schema, dict):
                self._diff_schema(b_schema, a_schema, path, label, method.upper(), report,
                                  before_spec, after_spec, 0)

    @staticmethod
    def _resolve(schema: dict, spec: dict) -> dict:
        ref = schema.get("$ref")
        if not isinstance(ref, str) or not ref.startswith("#/"):
            return schema
        node: Any = spec
        for part in ref[2:].split("/"):
            node = node.get(part) if isinstance(node, dict) else None
        return node if isinstance(node, dict) else {}

    def _diff_schema(
        self,
        before: dict,
        after: dict,
        endpoint: str,
        label: str,
        method: str | None,
        report: SpecDiffReport,
        before_spec: dict,
        after_spec: dict,
        depth: int,
    ) -> None:
        if depth > self._MAX_DEPTH or not isinstance(before, dict) or not isinstance(after, dict):
            return
        b_ref, a_ref = before.get("$ref"), after.get("$ref")
        if b_ref is not None and b_ref == a_ref:
            return  # same named component on both sides: diffed under components
        before = self._resolve(before, before_spec)
        after = self._resolve(after, after_spec)

        def add(ct: ChangeType, breaking: bool, detail: str, b: Any = None, a: Any = None) -> None:
            (report.breaking if breaking else report.additive).append(SpecChange(
                change_type=ct, breaking=breaking, endpoint=endpoint, method=method,
                detail=detail, before=b, after=a))

        b_type, a_type = before.get("type"), after.get("type")
        if b_type and a_type and b_type != a_type:
            add(ChangeType.CHANGED_FIELD_TYPE, True,
                f"{label}: type changed from '{b_type}' to '{a_type}'", b_type, a_type)
            return

        b_enum, a_enum = before.get("enum"), after.get("enum")
        if isinstance(b_enum, list) and isinstance(a_enum, list):
            for v in b_enum:
                if v not in a_enum:
                    add(ChangeType.REMOVED_ENUM_VALUE, True, f"{label}: enum value {v!r} removed", v)
            for v in a_enum:
                if v not in b_enum:
                    add(ChangeType.ADDED_ENUM_VALUE, False, f"{label}: enum value {v!r} added", None, v)

        b_props = before.get("properties") or {}
        a_props = after.get("properties") or {}
        b_req, a_req = set(before.get("required") or []), set(after.get("required") or [])
        for name in sorted(b_props):
            if name not in a_props:
                add(ChangeType.REMOVED_FIELD, True, f"{label}: field '{name}' was removed")
        for name in sorted(a_props):
            if name not in b_props:
                if name in a_req:
                    add(ChangeType.ADDED_REQUIRED_FIELD, True,
                        f"{label}: new required field '{name}' added — breaks existing callers")
                else:
                    add(ChangeType.ADDED_OPTIONAL_FIELD, False, f"{label}: optional field '{name}' added")
            else:
                if name in a_req and name not in b_req:
                    add(ChangeType.ADDED_REQUIRED_FIELD, True,
                        f"{label}: field '{name}' became required — breaks existing callers")
                self._diff_schema(b_props[name], a_props[name], endpoint, f"{label}.{name}", method,
                                  report, before_spec, after_spec, depth + 1)

        b_items, a_items = before.get("items"), after.get("items")
        if isinstance(b_items, dict) and isinstance(a_items, dict):
            self._diff_schema(b_items, a_items, endpoint, f"{label}[]", method, report,
                              before_spec, after_spec, depth + 1)

    @staticmethod
    def _load(path: str) -> dict:
        import yaml  # pyyaml in requirements.txt

        with open(path, encoding="utf-8") as f:
            if path.endswith((".yaml", ".yml")):
                return yaml.safe_load(f) or {}
            return json.load(f)


def print_diff_report(report: SpecDiffReport, fmt: str = "text") -> None:
    """Print a human-readable or JSON diff report to stdout."""
    if fmt == "json":
        print(json.dumps(report.to_dict(), indent=2))
        return

    # Text format
    total = len(report.breaking) + len(report.additive) + len(report.informational)
    if total == 0:
        print("No changes detected between specs.")
        return

    if report.breaking:
        print(f"\nBREAKING CHANGES ({len(report.breaking)}):")
        for c in report.breaking:
            meth = f"[{c.method}]" if c.method else ""
            print(f"  \u274c {meth} {c.endpoint} — {c.detail}")

    if report.additive:
        print(f"\nADDITIVE CHANGES ({len(report.additive)}):")
        for c in report.additive:
            meth = f"[{c.method}]" if c.method else ""
            print(f"  \u2705 {meth} {c.endpoint} — {c.detail}")

    if report.informational:
        print(f"\nINFORMATIONAL ({len(report.informational)}):")
        for c in report.informational:
            print(f"  \u2139\ufe0f  {c.endpoint} — {c.detail}")

    print()
    if report.has_breaking_changes:
        print("Run `cherenkov validate` to re-generate tests for affected endpoints.")
