[mypy]
python_version = 3.10
ignore_missing_imports = true
no_strict_optional = true
warn_unused_ignores = false
warn_redundant_casts = false

[mypy-cherenkov.enterprise.saml]
ignore_errors = true

[mypy-cherenkov.adapters.notifiers.*]
ignore_errors = true
