import pytest


def test_debug():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    pytest.main(['tests/unit/test_report_cmd.py::TestSelfTestCmd::test_tsc_failure_exits_1', '-v', '-s'])

if __name__ == '__main__':
    test_debug()
