from __future__ import annotations

from pydantic import BaseModel


class gRPCScenario(BaseModel):  # noqa: N801
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    service: str = ""
    rpc_name: str = ""
    input_message: str = ""
    proto_content: str = ""
    case_type: str = ""
    mutation_id: str = ""
    expected_status: int = 200
