from __future__ import annotations

import asyncio
import logging
import sqlite3
import time

from fastapi import APIRouter

_log = logging.getLogger(__name__)

router = APIRouter(tags=["data"])


@router.get("/api/v1/overview")
async def get_overview():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    from cherenkov.core.feedback_store import FeedbackStore
    from cherenkov.substrate.accounting import CostAccountant

    accountant = CostAccountant()
    kpi = accountant.get_governance_kpis()
    feedback = FeedbackStore()
    recent = feedback.get_all()[-10:] if feedback.get_all() else []

    return {
        "falsePositiveRate": kpi["false_positive_rate"],
        "maintenanceEfficiency": kpi["maintenance_efficiency"],
        "defectEscapeCount": kpi["defect_escape_count"],
        "totalVerdicts": kpi["total_verdicts"],
        "recentLearnings": [
            {
                "id": f.hitl_item_id,
                "action": f.action,
                "reason": f.reason,
                "timestamp": getattr(f, "timestamp", ""),
            }
            for f in recent
        ],
    }


@router.get("/api/v1/truth-map")
async def get_truth_map():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    from cherenkov.reflector.store import VerdictStore

    store = VerdictStore()
    try:
        idioms = store.get_idioms(limit=50)
    except Exception:
        _log.error("failed to load idioms for truth map", exc_info=True)
        idioms = []
    return [
        {
            "id": i.id,
            "pattern": i.pattern,
            "divergence_class": i.divergence_class.value
            if i.divergence_class
            else "unknown",
            "endpoint": i.endpoint,
            "confirm_count": i.confirm_count,
            "decay_score": i.decay_score,
        }
        for i in idioms
    ]


@router.get("/api/v1/failures")
async def get_failures():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    from cherenkov.core.contracts import VerdictOutcome
    from cherenkov.reflector.store import VerdictStore

    failure_type_map = {
        "CONTRACT_DRIFT": "CONTRACT_DRIFT",
        "AUTH_EXPIRY": "AUTH_EXPIRY",
        "STATE_SEQUENCING": "STATE_SEQUENCING",
        "NETWORK_FLAKY": "NETWORK_FLAKY",
        "ASSERTION_DRIFT": "ASSERTION_DRIFT",
    }

    store = VerdictStore()
    reject_val = VerdictOutcome.REJECT.value
    escaped_val = VerdictOutcome.ESCAPED_DEFECT.value

    def _query_failures():
        conn = sqlite3.connect(store.db_path, timeout=10.0)
        conn.row_factory = sqlite3.Row
        try:
            cursor = conn.execute(
                "SELECT id, endpoint, outcome, failure_class, detail, timestamp "
                "FROM verdicts WHERE outcome IN (?, ?) "
                "ORDER BY timestamp DESC LIMIT 50",
                (reject_val, escaped_val),
            )
            return [dict(r) for r in cursor.fetchall()]
        except sqlite3.Error:
            _log.error("failed to query recent failures from %s", store.db_path, exc_info=True)
            return []
        finally:
            conn.close()

    raw = await asyncio.to_thread(_query_failures)

    return [
        {
            "id": r["id"],
            "name": r["endpoint"] or r["id"],
            "failureType": failure_type_map.get(
                r.get("failure_class") or "", "ASSERTION_DRIFT"
            ),
            "diagnosis": r.get("detail") or "Failure detected during review.",
            "oldCode": "",
            "proposedCode": "",
            "hasAssertionWarning": False,
            "endpoint": r["endpoint"],
            "outcome": r["outcome"],
            "timestamp": r["timestamp"],
        }
        for r in raw
    ]


@router.get("/api/v1/memory")
async def get_memory():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    from cherenkov.reflector.store import VerdictStore

    store = VerdictStore()
    try:
        raw_idioms = store.get_idioms(limit=50)
    except Exception:
        _log.error("failed to load idioms for memory view", exc_info=True)
        raw_idioms = []

    idioms = [
        {
            "id": i.id,
            "text": i.pattern,
            "count": i.confirm_count,
            "decay": f"{i.decay_score:.0%}" if i.decay_score is not None else "ACTIVE",
        }
        for i in raw_idioms
    ]
    pairing = [
        {
            "context": "API conformance",
            "explanation": "Verify status codes, response schemas, and auth flows match the OpenAPI spec before approving a test.",
        },
        {
            "context": "False positive triage",
            "explanation": "When a test fails, cross-check the spec claim and actual response body to determine if the spec or the implementation is wrong.",
        },
    ]
    return {"idioms": idioms, "pairing": pairing}


@router.get("/api/v1/signals")
async def get_signals():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    from cherenkov.reflector.store import VerdictStore
    from cherenkov.substrate.accounting import CostAccountant

    store = VerdictStore()

    def _query_signals():
        conn = sqlite3.connect(store.db_path, timeout=5.0)
        conn.row_factory = sqlite3.Row
        try:
            cursor = conn.execute(
                "SELECT endpoint, duration_ms, timestamp FROM verdicts ORDER BY timestamp DESC LIMIT 20"
            )
            return [dict(r) for r in cursor.fetchall()]
        except sqlite3.Error:
            _log.error("failed to query performance signals from %s", store.db_path, exc_info=True)
            return []
        finally:
            conn.close()

    performance = []
    for r in await asyncio.to_thread(_query_signals):
        dur = r["duration_ms"] if r["duration_ms"] else 0
        baseline = 200
        performance.append(
            {
                "time": r["timestamp"] or "",
                "latency": dur,
                "baseline": baseline,
                "anomaly": dur > baseline * 3,
            }
        )

    visual = [
        {"id": "v1", "name": "Overview Dashboard", "difference": "0.0%", "status": "ok"},
        {"id": "v2", "name": "Divergences Table", "difference": "0.0%", "status": "ok"},
    ]

    accountant = CostAccountant()
    report = accountant.report
    total = report.request_count or 1
    coverage = [
        {
            "path": "/api/v1/*",
            "cherenkov": min(100, round((report.request_count / max(total, 1)) * 100)),
            "sdet": 0,
        },
    ]

    return {"performance": performance, "visual": visual, "coverage": coverage}


@router.get("/api/v1/visual/scenarios")
async def get_visual_scenarios():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    now = int(time.time())
    return [
        {
            "scenario_id": "vs-overview-001",
            "endpoint": "GET /overview",
            "vlm_kind": "harmless_shift",
            "verdict": "AUTO_APPROVE",
            "diff_pct": 0.4,
            "baseline_url": None,
            "current_url": None,
            "description": "Overview KPI card spacing adjusted by 2px — below threshold.",
            "timestamp": now - 3600,
        },
        {
            "scenario_id": "vs-divergences-002",
            "endpoint": "GET /divergences",
            "vlm_kind": "anomaly",
            "verdict": "HITL",
            "diff_pct": 8.2,
            "baseline_url": None,
            "current_url": None,
            "description": "Divergence table row color changed from red-500 to red-400 — possible branding drift.",
            "timestamp": now - 7200,
        },
        {
            "scenario_id": "vs-review-003",
            "endpoint": "GET /review",
            "vlm_kind": "harmless_shift",
            "verdict": "AUTO_APPROVE",
            "diff_pct": 0.1,
            "baseline_url": None,
            "current_url": None,
            "description": "Review gate button label truncation at 1280px viewport — cosmetic only.",
            "timestamp": now - 10800,
        },
        {
            "scenario_id": "vs-signals-004",
            "endpoint": "GET /signals",
            "vlm_kind": "redesign",
            "verdict": "HITL",
            "diff_pct": 22.7,
            "baseline_url": None,
            "current_url": None,
            "description": "Signals chart axis labels updated to ISO 8601 — significant layout change.",
            "timestamp": now - 14400,
        },
        {
            "scenario_id": "vs-memory-005",
            "endpoint": "GET /memory",
            "vlm_kind": "unknown",
            "verdict": "HITL",
            "diff_pct": 3.1,
            "baseline_url": None,
            "current_url": None,
            "description": "Memory screen idiom card padding inconsistency — needs human review.",
            "timestamp": now - 18000,
        },
    ]
