from __future__ import annotations

import os

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

router = APIRouter(tags=["static"])

_ui_dist = os.path.realpath(os.path.join(os.path.dirname(__file__), "..", "ui", "dist"))


def _resolve_within_dist(*parts: str) -> str | None:
    """Resolve a client-supplied path inside the built UI directory.

    Returns the real path, or None when it escapes `_ui_dist` (``..``
    segments, absolute paths, symlinks pointing outside).
    """
    candidate = os.path.realpath(os.path.join(_ui_dist, *parts))
    if candidate != _ui_dist and not candidate.startswith(_ui_dist + os.sep):
        return None
    return candidate


@router.get("/")
async def serve_index():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    index = os.path.join(_ui_dist, "index.html")
    if os.path.exists(index):
        return FileResponse(index)
    return {"status": "UI not built. Run `npm run build` in cherenkov/web/ui/."}


@router.get("/assets/{path:path}")
async def serve_assets(path: str):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    asset = _resolve_within_dist("assets", path)
    if asset and os.path.isfile(asset):
        return FileResponse(asset)
    raise HTTPException(status_code=404, detail="Asset not found")


@router.get("/{full_path:path}")
async def serve_spa_fallback(full_path: str):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    if full_path.startswith("api/"):
        raise HTTPException(status_code=404, detail="API endpoint not found")

    file_path = _resolve_within_dist(full_path)
    if file_path and os.path.isfile(file_path):
        return FileResponse(file_path)

    index = os.path.join(_ui_dist, "index.html")
    if os.path.exists(index):
        return FileResponse(index)
    return {"status": "UI not built. Run `npm run build` in cherenkov/web/ui/."}
