"""
cherenkov/truth/emitters/pr_comment.py — E4-2: PR-comment emitter.

Emit a Markdown summary suitable for posting as a PR comment when closing a
divergence is better handled by human review than by generating a test.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from cherenkov.core.contracts import DivergenceReport
from cherenkov.core.truth_model import TruthModel
from cherenkov.truth.emitters.interface import Emitter


class PRCommentEmitter(Emitter):
    """Emits a Markdown PR comment summarizing divergences for human review."""

    def emit(
        self,
        truth_model: TruthModel,
        output_path: Path,
        divergences: list[DivergenceReport] | None = None,
        **kwargs: Any,
    ) -> Path:
        lines = [
            "## CHERENKOV Divergence Report",
            "",
            "| Endpoint | Divergence | Severity | Description |",
            "|----------|------------|----------|-------------|",
        ]

        if divergences:
            for d in divergences:
                endpoint = d.endpoint_id or "unknown"  # type: ignore
                cls = (
                    d.divergence_class.value
                    if hasattr(d.divergence_class, "value")
                    else str(d.divergence_class)
                )
                sev = (
                    d.severity.value
                    if hasattr(d.severity, "value")
                    else str(d.severity)
                )
                desc = d.description.replace("|", "\\|") if d.description else ""  # type: ignore
                lines.append(f"| {endpoint} | {cls} | {sev} | {desc} |")
        else:
            lines.append("| _No divergences detected_ | | | |")

        lines.append("")
        lines.append("_Generated by CHERENKOV PRCommentEmitter_")

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines), encoding="utf-8")
        return output_path
