from __future__ import annotations

import os
import tempfile
from pathlib import Path

import pytest

os.environ.setdefault("CHERENKOV_RATE_LIMIT_ENABLED", "false")

# Never write to the developer's real ~/.cherenkov/runs.db during a test run.
# RunStore and DivergenceStore both resolve CHERENKOV_RUNS_DB at first use, so
# pointing it at a per-session temp dir keeps run records — and the divergence
# findings now persisted alongside them (#903) — out of the user's home. Before
# findings were stored this leaked only harmless scalars; now it would leak
# whole findings that /api/v1/divergences reads back.
os.environ.setdefault(
    "CHERENKOV_RUNS_DB",
    str(Path(tempfile.mkdtemp(prefix="cherenkov-tests-")) / "runs.db"),
)


def _ollama_reachable() -> bool:
    try:
        import json as _json
        import urllib.request

        req = urllib.request.Request("http://localhost:11434/api/tags", method="GET")
        resp = urllib.request.urlopen(req, timeout=2)
        data = _json.loads(resp.read().decode())
        return len(data.get("models", [])) > 0
    except Exception:
        return False


ollama_available = _ollama_reachable()


def pytest_configure(config):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    config.addinivalue_line("markers", "ollama: requires Ollama running on localhost:11434")


def pytest_collection_modifyitems(config, items):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    if ollama_available:
        return
    for item in items:
        if "test_judge_sample" in item.nodeid:
            item.add_marker(pytest.mark.skip(reason="Ollama not reachable (needed by LLM-judge evals)"))
        if "test_graphql_generate_integration" in item.nodeid:
            item.add_marker(pytest.mark.skip(reason="Ollama not reachable (needed by E2E generation)"))


@pytest.fixture(autouse=True)
def _restore_logger_config():
    from cherenkov.core.errors import LoggerConfig
    original = LoggerConfig.suppress_stderr
    yield
    LoggerConfig.suppress_stderr = original
