#!/usr/bin/env python3
"""
smoke_test_review_non_demo.py — verifies the review dashboard boots without --demo flag.
"""

import os
import subprocess
import time

import requests


def main():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    print("Starting review dashboard in non-demo mode...")
    proc = subprocess.Popen(
        ["./bin/cherenkov", "review", "review", "--port", "8005"],
        env={**os.environ, "PYTHONPATH": "."},
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    healthy = False
    for _ in range(30):
        try:
            resp = requests.get("http://localhost:8005/", timeout=2)
            if resp.status_code == 200:
                healthy = True
                print("Dashboard is healthy and online.")
                break
        except Exception:
            time.sleep(1)

    proc.terminate()
    proc.wait(timeout=5)

    if not healthy:
        stdout, stderr = proc.communicate()
        print(f"Stdout:\n{stdout.decode()}")
        print(f"Stderr:\n{stderr.decode()}")
        raise AssertionError("Review dashboard failed to boot in non-demo mode.")

    print("Smoke test passed.")


if __name__ == "__main__":
    main()
