//go:build !ignore_autogenerated

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *ConformanceCheck) DeepCopyInto(out *ConformanceCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ConformanceCheck) DeepCopy() *ConformanceCheck {
	if in == nil {
		return nil
	}
	out := new(ConformanceCheck)
	in.DeepCopyInto(out)
	return out
}

func (in *ConformanceCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ConformanceCheckList) DeepCopyInto(out *ConformanceCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConformanceCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ConformanceCheckList) DeepCopy() *ConformanceCheckList {
	if in == nil {
		return nil
	}
	out := new(ConformanceCheckList)
	in.DeepCopyInto(out)
	return out
}

func (in *ConformanceCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ConformanceCheckSpec) DeepCopyInto(out *ConformanceCheckSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.Gates != nil {
		in, out := &in.Gates, &out.Gates
		*out = make([]Gate, len(*in))
		copy(*out, *in)
	}
	if in.LLMConcurrency != nil {
		in, out := &in.LLMConcurrency, &out.LLMConcurrency
		*out = new(int32)
		**out = **in
	}
}

func (in *ConformanceCheckSpec) DeepCopy() *ConformanceCheckSpec {
	if in == nil {
		return nil
	}
	out := new(ConformanceCheckSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ConformanceCheckStatus) DeepCopyInto(out *ConformanceCheckStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRun != nil {
		in, out := &in.LastRun, &out.LastRun
		*out = (*in).DeepCopy()
	}
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = new(CheckResult)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ConformanceCheckStatus) DeepCopy() *ConformanceCheckStatus {
	if in == nil {
		return nil
	}
	out := new(ConformanceCheckStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *CheckResult) DeepCopyInto(out *CheckResult) {
	*out = *in
	if in.Divergences != nil {
		in, out := &in.Divergences, &out.Divergences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}
