from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


@dataclass
class MobileApp:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    app_id: str
    name: str
    platform: Literal["android", "ios"]
    version: str
    package_path: str


@dataclass
class MobileScreen:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    screen_id: str
    name: str
    elements: list[dict]
    navigation: list[str]


@dataclass
class MobileFlow:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    flow_id: str
    name: str
    screens: list[str]
    actions: list[dict]
