"""CHERENKOV web/pr_comments.py — Spec coverage PR-comment integration (#766).

On pull_request events (opened / ready_for_review / synchronize) the GitHub
webhook consumer computes a spec coverage report from the live divergence
corpus and posts a concise markdown comment to the PR, so reviewers see at a
glance how much of the spec surface is tested and whether new divergences lurk.

The comment text reuses cherenkov.web.coverage_map so the web dashboard and the
PR comment never disagree about the numbers (single source of truth). This
keeps the Phase 14 coverage surface consistent across UI + CI feedback loops.
"""

from __future__ import annotations

from typing import Any

from cherenkov.web import coverage_map as coverage_service

_GITHUB_API = "https://api.github.com"


def _get_github_token() -> str:
    from cherenkov.core.settings import get_settings

    return get_settings().GITHUB_TOKEN


def format_coverage_comment(coverage: dict[str, Any]) -> str:
    """Render a spec coverage map as a concise GitHub markdown comment.

    Args:
        coverage: Coverage map dictionary from build_coverage_map.

    Returns:
        Formatted markdown comment string.
    """
    pct = coverage.get("coveragePct", 0.0)
    tested = coverage.get("testedCount", 0)
    total = coverage.get("totalEndpoints", 0)
    open_issues = coverage.get("openIssueCount", 0)

    lines: list[str] = []
    lines.append("## Spec coverage report")
    lines.append("")
    lines.append(
        f"**Coverage:** `{pct:.1f}%` ({tested}/{total} endpoints probed) · "
        f"**Open divergences:** {open_issues}"
    )
    lines.append("")

    gaps = [e for e in coverage.get("endpoints", []) if not e.get("tested")]
    if gaps:
        lines.append("### Untested endpoints (gaps)")
        lines.append("")
        lines.append("| Method | Path |")
        lines.append("|--------|------|")
        for ep in sorted(gaps, key=lambda e: (e["method"], e["path"]))[:20]:
            lines.append(f"| {ep['method']} | {ep['path']} |")
        if len(gaps) > 20:
            lines.append(f"| _..._ | _{len(gaps) - 20} more_ |")
        lines.append("")

    active = [
        e
        for e in coverage.get("endpoints", [])
        if e.get("activeSeverity")
    ]
    if active:
        lines.append("### Endpoints with active divergences")
        lines.append("")
        lines.append("| Method | Path | Severity | Divergences |")
        lines.append("|--------|------|----------|-------------|")
        for ep in sorted(active, key=lambda e: e["activeSeverity"] or "z"):
            lines.append(
                f"| {ep['method']} | {ep['path']} | {ep['activeSeverity']} | "
                f"{ep.get('divergenceCount', 0)} |"
            )
        lines.append("")

    lines.append(
        "Generated by [CHERENKOV-QA](https://github.com/moaidmoatasem/cherenkov-qa)."
    )
    return "\n".join(lines)


def build_comment_body() -> str:
    """Compute the coverage map and format it as a PR comment body.

    Returns:
        Formatted PR comment markdown string.
    """
    summary = coverage_service.build_coverage_map()
    return format_coverage_comment(summary)


class GitHubClient:
    """Thin wrapper over the GitHub REST API for posting PR comments.

    Isolated from I/O so it can be unit-tested without network access.
    """

    def __init__(self, token: str | None = None, base_url: str = _GITHUB_API):
        """Initialize GitHubClient with personal token and base API URL.

        Args:
            token: Optional GitHub Personal Access Token string.
            base_url: Base GitHub API URL string.
        """
        self._token = token or _get_github_token()
        self._base_url = base_url.rstrip("/")

    def post_pr_comment(self, repo: str, pr_number: int, body: str) -> dict[str, Any]:
        """Post (or update) a comment on a pull request.

        Args:
            repo: Target repository full name (e.g. 'org/repo').
            pr_number: Pull request issue number integer.
            body: Comment markdown text body.

        Returns:
            GitHub API response JSON dictionary.

        Raises:
            RuntimeError: If GITHUB_TOKEN is missing or HTTP request fails.
        """
        import requests

        if not self._token:
            raise RuntimeError("GITHUB_TOKEN is not configured; cannot post PR comment")

        url = f"{self._base_url}/repos/{repo}/issues/{pr_number}/comments"
        headers = {
            "Authorization": f"Bearer {self._token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        resp = requests.post(url, json={"body": body}, headers=headers, timeout=15)
        resp.raise_for_status()
        return resp.json()


def post_coverage_comment(repo: str, pr_number: int) -> dict[str, Any]:
    """Convenience: compute the coverage map + post a formatted comment.

    Args:
        repo: Repository identifier string.
        pr_number: Pull request number.

    Returns:
        GitHub API response dictionary.
    """
    client = GitHubClient()
    body = build_comment_body()
    return client.post_pr_comment(repo, pr_number, body)


def should_comment(action: str) -> bool:
    """Whether a given pull_request action should trigger a coverage comment.

    Args:
        action: GitHub pull_request event action string.

    Returns:
        True if action should trigger comment posting, False otherwise.
    """
    return action in {"opened", "ready_for_review", "synchronize", "reopened"}
