from __future__ import annotations

import dataclasses
import enum
from typing import Any


class ThreatCategory(enum.Enum):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    PROMPT_INJECTION = "prompt_injection"
    DATA_EXFILTRATION = "data_exfiltration"
    COMMAND_INJECTION = "command_injection"
    SPEC_MANIPULATION = "spec_manipulation"
    TAUTOLOGICAL_TEST = "tautological_test"


class Severity(enum.Enum):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclasses.dataclass
class InjectionPayload:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    id: str
    category: ThreatCategory
    payload: str
    description: str
    severity: Severity = Severity.MEDIUM


@dataclasses.dataclass
class DetectionResult:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    payload_id: str
    category: ThreatCategory
    detected: bool
    severity: Severity
    detail: str
    test_code_snippet: str = ""


@dataclasses.dataclass
class AdversarialReport:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    results: list[DetectionResult]
    model: str
    timestamp: str
    garak_available: bool = False
    garak_findings: list[dict[str, Any]] = dataclasses.field(default_factory=list)

    def pass_rate(self) -> float:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        if not self.results:
            return 1.0
        return sum(1 for r in self.results if not r.detected) / len(self.results)

    def critical_findings(self) -> list[DetectionResult]:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        return [r for r in self.results if r.detected and r.severity in (Severity.HIGH, Severity.CRITICAL)]

    def to_dict(self) -> dict[str, Any]:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        return {
            "pass_rate": self.pass_rate(),
            "total_payloads": len(self.results),
            "detected": sum(1 for r in self.results if r.detected),
            "passed": sum(1 for r in self.results if not r.detected),
            "critical": len(self.critical_findings()),
            "garak_available": self.garak_available,
            "garak_findings": self.garak_findings,
            "results": [
                {
                    "payload_id": r.payload_id,
                    "category": r.category.value,
                    "detected": r.detected,
                    "severity": r.severity.value,
                    "detail": r.detail,
                }
                for r in self.results
            ],
            "model": self.model,
            "timestamp": self.timestamp,
        }
