"""
cherenkov/continuity/pr_diff_action.py — E4-5: Behavioral diff on PR (GitHub Action).
Authority: v3.1 + delta.

On a PR, comment which endpoints changed actual behaviour vs base.
Distinguishes intended vs unintended drift.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from cherenkov.core.contracts import DivergenceReport
from cherenkov.core.errors import get_logger
from cherenkov.stages.map_cmd import build_truth_model


class BehavioralDiff:
    """Computes behavioral diff between a base Truth Model and a PR Truth Model."""

    def __init__(self, base_sources: dict[str, list[str]], pr_sources: dict[str, list[str]]):
        self._base_sources = base_sources
        self._pr_sources = pr_sources
        self._log = get_logger("behavioral-diff")

    def compute(self) -> list[dict[str, Any]]:
        base_tm = build_truth_model(self._base_sources)
        pr_tm = build_truth_model(self._pr_sources)

        diffs: list[dict[str, Any]] = []

        base_endpoints = {n.label: n for n in base_tm.get_endpoints()}
        pr_endpoints = {n.label: n for n in pr_tm.get_endpoints()}

        for label, pr_node in pr_endpoints.items():
            base_node = base_endpoints.get(label)

            pr_status_claims = [c for c in pr_node.claims if c.predicate.startswith("observed_status:")]
            base_status_claims = [c for c in base_node.claims if c.predicate.startswith("observed_status:")] if base_node else []

            pr_status = pr_status_claims[0].value.get("status") if pr_status_claims else None
            base_status = base_status_claims[0].value.get("status") if base_status_claims else None

            if pr_status != base_status:
                diffs.append({
                    "endpoint": label,
                    "change": "status",
                    "base": base_status,
                    "pr": pr_status,
                    "intended": False,
                    "description": f"Status changed from {base_status} to {pr_status}",
                })

        for label, base_node in base_endpoints.items():
            if label not in pr_endpoints:
                base_status_claims = [c for c in base_node.claims if c.predicate.startswith("observed_status:")]
                base_status = base_status_claims[0].value.get("status") if base_status_claims else None
                diffs.append({
                    "endpoint": label,
                    "change": "removed",
                    "base": base_status,
                    "pr": None,
                    "intended": True,
                    "description": f"Endpoint {label} removed from PR",
                })

        return diffs

    def render_markdown(self, diffs: list[dict[str, Any]]) -> str:
        lines = [
            "## CHERENKOV Behavioral Diff Report",
            "",
            "| Endpoint | Change | Base | PR | Intended? | Description |",
            "|----------|--------|------|-----|-----------|-------------|",
        ]
        for d in diffs:
            intended_str = "Yes" if d.get("intended") else "No"
            lines.append(
                f"| {d['endpoint']} | {d['change']} | {d['base']} | {d['pr']} | "
                f"{intended_str} | {d['description']} |"
            )
        lines.append("")
        lines.append("_Generated by CHERENKOV BehavioralDiff_")
        return "\n".join(lines)


def run_pr_diff(
    base_spec: str | None = None,
    pr_spec: str | None = None,
    output_path: str | None = None,
) -> int:
    """CLI entry point for the PR diff action."""
    log = get_logger("pr-diff")

    base_sources: dict[str, list[str]] = {}
    pr_sources: dict[str, list[str]] = {}

    if base_spec:
        base_sources["openapi"] = [base_spec]
    if pr_spec:
        pr_sources["openapi"] = [pr_spec]

    diff = BehavioralDiff(base_sources, pr_sources)
    diffs = diff.compute()
    markdown = diff.render_markdown(diffs)

    output = Path(output_path or "pr_diff_report.md")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")

    log.info("pr diff report written", path=str(output), diff_count=len(diffs))
    print(markdown)
    return 0
