apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conformancecheck-operator
rules:
- apiGroups: ["cherenkov.io"]
  resources: ["conformancechecks"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
