from __future__ import annotations

from pydantic import BaseModel


class GraphQLScenario(BaseModel):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    operation_name: str
    kind: str  # query/mutation/subscription
    scenario_type: str  # happy_path | null_fields | pagination | error | auth
    gql_query: str
    variables: dict
    expected_response_structure: dict
