from __future__ import annotations

import asyncio
import json
from functools import lru_cache
from typing import TYPE_CHECKING

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from cherenkov.chat.adapters.sqlite_memory import SQLiteConversationMemory
from cherenkov.chat.agent import QAChatAgent
from cherenkov.chat.guard import get_guard
from cherenkov.chat.ports.memory import ConversationMemory
from cherenkov.core.errors import get_logger

if TYPE_CHECKING:  # pragma: no cover
    from cherenkov.substrate.router import SubstrateRouter

logger = get_logger("CHAT_API")

router = APIRouter()


class ChatMessageRequest(BaseModel):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    content: str = Field(..., min_length=1, description="Message content")


class CreateSessionRequest(BaseModel):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    persona_id: str = Field(
        default="qa_assistant", description="Persona to use for this session"
    )


@lru_cache(maxsize=1)
def get_memory() -> ConversationMemory:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    return SQLiteConversationMemory()


@lru_cache(maxsize=1)
def get_substrate_router() -> SubstrateRouter | None:
    """The inference router for the web chat path.

    Omitting this is why the dashboard replied to every message with the
    literal string "[MOCK] AI substrate unavailable" — `QAChatAgent` falls
    through to `_fallback_llm` when no router is supplied. The CLI REPL
    (`chat/cli_repl.py:14`) and the LangChain tool both injected one; only the
    web path did not. Constructed lazily and cached so an unavailable backend
    degrades to the existing fallback instead of failing app startup.
    """
    try:
        from cherenkov.substrate.router import SubstrateRouter

        return SubstrateRouter()
    except Exception:  # never let chat wiring break API startup
        logger.warning(
            "substrate router unavailable; chat will use the offline fallback",
            exc_info=True,
        )
        return None


def get_agent(memory: ConversationMemory = Depends(get_memory)) -> QAChatAgent:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    return QAChatAgent(memory=memory, substrate_router=get_substrate_router())


@router.post("/api/v1/chat/sessions")
async def create_session(
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    body: CreateSessionRequest,
    agent: QAChatAgent = Depends(get_agent),
):
    session = await asyncio.to_thread(agent.create_session, body.persona_id)
    return {"session_id": session.session_id, "persona_id": session.persona_id}


@router.get("/api/v1/chat/sessions")
async def list_sessions(
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    limit: int = 20,
    memory: ConversationMemory = Depends(get_memory),
):
    sessions = await asyncio.to_thread(memory.list_sessions, limit)
    return {"sessions": [s.to_dict() for s in sessions]}


@router.get("/api/v1/chat/sessions/{session_id}")
async def get_session(
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    session_id: str,
    agent: QAChatAgent = Depends(get_agent),
):
    session = await asyncio.to_thread(agent.get_session, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    return session.to_dict()


@router.post("/api/v1/chat/sessions/{session_id}/messages")
async def send_message(
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    session_id: str,
    body: ChatMessageRequest,
    agent: QAChatAgent = Depends(get_agent),
):
    session = await asyncio.to_thread(agent.get_session, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    guard = get_guard()
    guard_result = guard.check_tool_call(
        "chat_send_message",
        {"session_id": session_id, "content_length": len(body.content)},
    )
    if not guard_result.allowed:
        raise HTTPException(status_code=403, detail=guard_result.reason)
    assistant_msg = await asyncio.to_thread(agent.chat, session_id, body.content)
    return {"role": "assistant", "content": assistant_msg.content}


@router.get("/api/v1/chat/sessions/{session_id}/messages")
async def get_messages(
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    session_id: str,
    limit: int = 50,
    agent: QAChatAgent = Depends(get_agent),
    memory: ConversationMemory = Depends(get_memory),
):
    session = await asyncio.to_thread(agent.get_session, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    messages = await asyncio.to_thread(memory.get_messages, session_id, limit)
    return {"messages": [m.to_dict() for m in messages]}


@router.post("/api/v1/chat/sessions/{session_id}/stream")
async def stream_chat(
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    session_id: str,
    body: ChatMessageRequest,
    agent: QAChatAgent = Depends(get_agent),
):
    session = await asyncio.to_thread(agent.get_session, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    guard = get_guard()
    guard_result = guard.check_tool_call(
        "chat_stream", {"session_id": session_id, "content_length": len(body.content)}
    )
    if not guard_result.allowed:
        raise HTTPException(status_code=403, detail=guard_result.reason)

    async def event_stream():
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        async for token in agent.chat_stream(session_id, body.content):
            yield f"event: token\ndata: {json.dumps({'token': token})}\n\n"
        yield f"event: complete\ndata: {json.dumps({})}\n\n"

    return StreamingResponse(event_stream(), media_type="text/event-stream")


@router.post("/api/v1/chat/sessions/{session_id}/close")
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
async def close_session(
    session_id: str,
    agent: QAChatAgent = Depends(get_agent),
    memory: ConversationMemory = Depends(get_memory),
):
    session = await asyncio.to_thread(agent.get_session, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    await asyncio.to_thread(memory.close_session, session_id)
    return {"status": "closed"}
