"""Application-level Role-Based Access Control for CHERENKOV.

Enforcement decision (issue #810): HTTP request authorization is enforced
through the existing ``require_role`` dependency in
``cherenkov/web/auth/deps.py`` (role-hierarchy check wired into every
route handler), NOT through this module. This engine provides the
permission-level model (role -> permission mapping) for application and
CLI layers, e.g. the ``enterprise rbac assign`` command. The web Role
vocabulary (viewer/reviewer/admin) and this engine's Role vocabulary
(admin/engineer/viewer/read_only) are intentionally kept separate; a
unified model would invent new API surface and is out of scope.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from cherenkov.core.errors import get_logger

log = get_logger(__name__)


class Role(str, Enum):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    ADMIN = "admin"
    ENGINEER = "engineer"
    VIEWER = "viewer"
    READ_ONLY = "read_only"


class Permission(str, Enum):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    # HITL actions
    HITL_LIST = "hitl:list"
    HITL_APPROVE = "hitl:approve"
    HITL_REJECT = "hitl:reject"
    # Validation
    VALIDATE_RUN = "validate:run"
    VALIDATE_VIEW = "validate:view"
    # MCP tools
    MCP_LIST = "mcp:list"
    MCP_PUBLISH = "mcp:publish"
    # Enterprise
    RBAC_MANAGE = "rbac:manage"
    AUDIT_VIEW = "audit:view"
    AUDIT_EXPORT = "audit:export"
    GDPR_MANAGE = "gdpr:manage"
    SOC2_GENERATE = "soc2:generate"
    # Config
    CONFIG_READ = "config:read"
    CONFIG_WRITE = "config:write"


# Default role-permission mapping
ROLE_PERMISSIONS: dict[Role, set[Permission]] = {
    Role.ADMIN: {
        Permission.HITL_LIST,
        Permission.HITL_APPROVE,
        Permission.HITL_REJECT,
        Permission.VALIDATE_RUN,
        Permission.VALIDATE_VIEW,
        Permission.MCP_LIST,
        Permission.MCP_PUBLISH,
        Permission.RBAC_MANAGE,
        Permission.AUDIT_VIEW,
        Permission.AUDIT_EXPORT,
        Permission.GDPR_MANAGE,
        Permission.SOC2_GENERATE,
        Permission.CONFIG_READ,
        Permission.CONFIG_WRITE,
    },
    Role.ENGINEER: {
        Permission.HITL_LIST,
        Permission.HITL_APPROVE,
        Permission.HITL_REJECT,
        Permission.VALIDATE_RUN,
        Permission.VALIDATE_VIEW,
        Permission.MCP_LIST,
        Permission.MCP_PUBLISH,
        Permission.AUDIT_VIEW,
        Permission.CONFIG_READ,
    },
    Role.VIEWER: {
        Permission.HITL_LIST,
        Permission.VALIDATE_VIEW,
        Permission.MCP_LIST,
        Permission.AUDIT_VIEW,
        Permission.CONFIG_READ,
    },
    Role.READ_ONLY: {
        Permission.VALIDATE_VIEW,
        Permission.CONFIG_READ,
    },
}


@dataclass
class User:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    id: str
    name: str
    email: str
    role: Role = Role.VIEWER
    teams: list[str] = field(default_factory=list)
    saml_assertion: str = ""


class RBACEngine:
    """Application-level RBAC enforcement.

    Integrates with SAML SSO for identity and provides permission checks
    across all CHERENKOV subsystems.
    """

    def __init__(self):
        self._users: dict[str, User] = {}

    def register_user(self, user: User) -> None:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        self._users[user.id] = user
        log.info("Registered user", user_id=user.id, role=user.role.value)

    def get_user(self, user_id: str) -> User | None:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        return self._users.get(user_id)

    def remove_user(self, user_id: str) -> bool:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        if user_id in self._users:
            del self._users[user_id]
            return True
        return False

    def list_users(self) -> list[User]:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        return list(self._users.values())

    def has_permission(self, user_id: str, permission: Permission) -> bool:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        user = self._users.get(user_id)
        if user is None:
            return False
        return permission in ROLE_PERMISSIONS.get(user.role, set())

    def require_permission(self, user_id: str, permission: Permission) -> None:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        if not self.has_permission(user_id, permission):
            raise PermissionError(
                f"User {user_id} lacks required permission: {permission.value}"
            )

    def set_role(self, user_id: str, role: Role) -> bool:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        user = self._users.get(user_id)
        if user is None:
            return False
        user.role = role
        log.info("Role changed", user_id=user_id, role=role.value)
        return True

    def user_has_any(self, user_id: str, permissions: list[Permission]) -> bool:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        return any(self.has_permission(user_id, p) for p in permissions)


# Global singleton
_engine = RBACEngine()


def get_rbac() -> RBACEngine:
    return _engine
