#!/usr/bin/env python3
"""
check_cli_flags.py -- CLI-flag docs parity checker.

Extends check_cli_docs.py (which only cross-references top-level *command
names*) to also verify that every *flag* documented for a command in the CLI
reference actually exists on the real Click command.

Checks, per command section in docs-site/docs/cli/reference.md:

  1. Every `--flag` named in a "**Flags:**" table resolves to that command's
     real Click options (opts | secondary_opts, so `--no-repair` beside
     `--repair` counts as existing).
  2. For a group command whose section table describes a subcommand (e.g.
     `guardian` documents `start`'s flags), documented flags are matched
     against the union of all of that command's flags, since the reference
     tables may describe either the command or one of its subcommands.

Exit 0 = every documented flag exists, 1 = flag drift found.
"""

from __future__ import annotations

import os
import re
import sys

_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
_REFERENCE_PATH = os.path.join(_REPO_ROOT, "docs-site", "docs", "cli", "reference.md")

# Click exposes --help on every command; the reference repeats it as a global
# option. It is not part of any per-command param list, so ignore it here.
_HELP_FLAGS = {"--help"}


def _real_flags_by_command(cli) -> dict[str, set[str]]:
    """Flatten the Click CLI into {command_ref: {long flag options}}.

    command_ref mirrors the documented spelling (`certify`, `guardian`,
    `hitl list`, `mcp publish`). Per-subcommand keys exist, and each group's
    bare key is the union of every descendant's flags (a section table may
    describe the group or a specific subcommand).
    """
    out: dict[str, set[str]] = {}

    def visit(cmd, prefix: str) -> None:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        if prefix:
            opts = set()
            for p in getattr(cmd, "params", []):
                for o in (*getattr(p, "opts", []), *getattr(p, "secondary_opts", [])):
                    if o.startswith("--"):
                        opts.add(o)
            out.setdefault(prefix, set()).update(opts)
        if hasattr(cmd, "commands"):
            for name, sub in cmd.commands.items():
                visit(sub, (prefix + " " + name).strip())

    visit(cli, "")

    # Roll each subcommand's flags up into its parent group key, so a bare
    # `guardian` table that really documents `guardian start` still validates.
    for key, flags in list(out.items()):
        if " " in key:
            parent = key.split(" ", 1)[0]
            out.setdefault(parent, set()).update(flags)
    return out


_CMD_RE = re.compile(r"^###\s+`([a-z][\w-]*(?:\s+[a-z][\w-]*)?)`\s*$")


def _iter_doc_flags(content: str):
    """Yield (command_ref, [long flags documented in its Flags: table])."""
    current = None
    in_flags = False
    pending: list[str] = []
    for line in content.splitlines():
        m = _CMD_RE.match(line)
        if m:
            if current and pending:
                yield current, pending
            current = m.group(1).strip()
            in_flags = False
            pending = []
            continue
        if current is None:
            continue
        if line.strip() == "**Flags:**":
            in_flags = True
            continue
        if in_flags and line.startswith("|"):
            for token in re.findall(r"(?<![\w-])--[a-z][\w-]*", line):
                if token not in _HELP_FLAGS:
                    pending.append(token)
        elif in_flags and re.match(r"^\s*(#{3,6}\s|\w+ \*\*|```)", line):
            in_flags = False
    if current:
        yield current, pending


    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
def main() -> int:
    """Placeholder docstring.

:return: <description>"""
    if _REPO_ROOT not in sys.path:
        sys.path.insert(0, _REPO_ROOT)
    try:
        from cherenkov.cli.core import _register_commands, cli
    except Exception as exc:  # pragma: no cover - defensive
        print(f"[FAIL] Could not load CLI parser: {exc}")
        return 1
    try:
        _register_commands()
    except Exception as exc:  # pragma: no cover - defensive
        print(f"[FAIL] Could not register CLI commands: {exc}")
        return 1
    if not os.path.isfile(_REFERENCE_PATH):
        print(f"[FAIL] {_REFERENCE_PATH} not found")
        return 1
    with open(_REFERENCE_PATH, encoding="utf-8") as f:
        content = f.read()

    real = _real_flags_by_command(cli)
    errors = []
    checked = 0
    
    # 1. Check reference.md Flags tables
    for command, flags in _iter_doc_flags(content):
        if not flags:
            continue
        if "<" in command:  # e.g. a table heading that isn't a CLI ref
            continue
        real_opts = real.get(command, set())
        if command not in real:
            errors.append(
                f"[{command}] documents flags {sorted(flags)} but has no such "
                "command/flags in the CLI parser (documented as a command)."
            )
            continue
        for flag in flags:
            checked += 1
            if flag not in real_opts:
                errors.append(
                    f"[{command}] documented flag `{flag}` does not exist in CLI "
                    f"(has: {sorted(real_opts) if real_opts else 'none'})"
                )

    # 2. Check all other .md files for inline `cherenkov <cmd> --flag` uses
    import glob
    # Archived/planning/vision docs are point-in-time records: they may cite
    # commands or flags that never shipped or were later renamed. Excluding
    # them keeps the gate scoped to docs that read as current, runnable
    # instructions.
    _EXCLUDED_DIRS = ("_archive", "vision", "plans")
    _md_files = (
        glob.glob(os.path.join(_REPO_ROOT, "docs", "**", "*.md"), recursive=True)
        + glob.glob(os.path.join(_REPO_ROOT, "skills", "**", "*.md"), recursive=True)
    )
    md_files = [
        f
        for f in _md_files
        if not any(
            os.sep + d + os.sep in os.path.relpath(f, _REPO_ROOT) for d in _EXCLUDED_DIRS
        )
    ]

    inline_re = re.compile(r"(?:python\s+cherenkov\.py|cherenkov|\./bin/cherenkov)\s+([a-z][\w-]*(?:\s+[a-z][\w-]*)?)\s+.*?(--[a-z][\w-]+)")
    for md_file in md_files:
        with open(md_file, encoding="utf-8", errors="ignore") as f:
            for line_no, line in enumerate(f, 1):
                for match in inline_re.finditer(line):
                    command, flag = match.groups()
                    if flag in _HELP_FLAGS:
                        continue
                    real_opts = real.get(command, set())
                    if command not in real:
                        errors.append(
                            f"{os.path.relpath(md_file, _REPO_ROOT)}:{line_no} uses command '{command}' which doesn't exist."
                        )
                    elif flag not in real_opts:
                        errors.append(
                            f"{os.path.relpath(md_file, _REPO_ROOT)}:{line_no} uses flag '{flag}' on command '{command}' but it doesn't exist "
                            f"(has: {sorted(real_opts) if real_opts else 'none'})"
                        )
                        checked += 1
    # 3. Check CI integration templates — the files users copy verbatim into
    #    their pipelines. These were previously unguarded, which is how the
    #    Jenkins shared library shipped a `--export-jira` option that exists on
    #    no command: the invocation fails, and the surrounding try/catch reports
    #    it as a conformance failure rather than a usage error.
    ci_files = sorted(
        glob.glob(os.path.join(_REPO_ROOT, "ci", "**", "*.yml"), recursive=True)
        + glob.glob(os.path.join(_REPO_ROOT, "ci", "**", "*.yaml"), recursive=True)
        + glob.glob(os.path.join(_REPO_ROOT, "ci", "**", "*.groovy"), recursive=True)
        + glob.glob(os.path.join(_REPO_ROOT, "action.yml"))
    )
    # `cherenkov <cmd>` anywhere in the file. The \s+ matters: it keeps
    # `pip install cherenkov-qa` from parsing as a command invocation.
    cmd_re = re.compile(r"(?:cherenkov|\./bin/cherenkov)\s+([a-z][\w-]*(?:\s+[a-z][\w-]*)?)")
    flag_re = re.compile(r"(--[a-z][\w-]+)")
    # Groovy/shell string appends: `cmd += " --export-jira"`. The flag sits on a
    # line with no command on it, so line-local matching cannot attribute it.
    append_re = re.compile(r"\+=\s*[\"'][^\"']*--[a-z]")

    def _strip_comment(line: str) -> str:
        """Drop comments so prose cannot parse as an invocation.

        Without this, `// ... assuming cherenkov is installed on the agent`
        reads as a command named "is installed", which made the Jenkins file
        look multi-command and silently disabled the append check below.
        """
        if line.lstrip().startswith(("//", "#")):
            return ""
        line = re.sub(r"\s+//(?!/).*$", "", line)  # groovy trailing, keeps http://
        line = re.sub(r"\s+#\s.*$", "", line)  # yaml trailing
        return line

    for ci_file in ci_files:
        rel = os.path.relpath(ci_file, _REPO_ROOT)
        with open(ci_file, encoding="utf-8", errors="ignore") as f:
            raw_lines = f.readlines()

        # Join backslash continuations into logical lines, keeping the line
        # number of the line that started them. action.yml spreads a single
        # `cherenkov validate \` invocation across 15 lines this way.
        logical: list[tuple[int, str]] = []
        buf, start = "", 0
        for line_no, line in enumerate(raw_lines, 1):
            stripped = _strip_comment(line.rstrip("\n"))
            if not buf:
                start = line_no
            if stripped.rstrip().endswith("\\"):
                buf += stripped.rstrip()[:-1] + " "
                continue
            logical.append((start, buf + stripped))
            buf = ""
        if buf:
            logical.append((start, buf))

        def _check(command: str, flag: str, line_no: int) -> None:
            nonlocal checked
            if flag in _HELP_FLAGS:
                return
            real_opts = real.get(command, set())
            if command not in real:
                errors.append(f"{rel}:{line_no} uses command '{command}' which doesn't exist.")
                return
            checked += 1
            if flag not in real_opts:
                errors.append(
                    f"{rel}:{line_no} uses flag '{flag}' on command '{command}' but it "
                    f"doesn't exist (has: {sorted(real_opts) if real_opts else 'none'})"
                )

        commands_in_file: set[str] = set()
        for line_no, line in logical:
            match = cmd_re.search(line)
            if not match:
                continue
            # Prefer a two-word command (`train run`) when one exists.
            tokens = match.group(1).split()
            command = tokens[0]
            if len(tokens) == 2 and " ".join(tokens) in real:
                command = " ".join(tokens)
            commands_in_file.add(command)
            # Every flag after the command on this logical line belongs to it.
            for flag in flag_re.findall(line[match.end(1):]):
                _check(command, flag, line_no)

        # Appended flags can only be attributed unambiguously when the file
        # invokes exactly one command. Staying silent otherwise keeps the gate
        # free of false positives on multi-command templates.
        if len(commands_in_file) == 1:
            sole = next(iter(commands_in_file))
            for line_no, line in enumerate(raw_lines, 1):
                if append_re.search(line):
                    for flag in flag_re.findall(line):
                        _check(sole, flag, line_no)

    print(f"Checked {checked} documented flags across the CLI reference.")
    if errors:
        print(f"\n[FAIL] {len(errors)} flag drift issue(s):")
        for e in errors:
            print(f"  * {e}")
        print(f"\nFix the markdown files so every documented flag is a real Click option.")
        return 1
    print("[PASS] every documented CLI flag exists on the real Click command.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
