from __future__ import annotations

from collections.abc import Callable
from typing import Protocol

from cherenkov.core.events import CHERENKOVEvent


class EventBus(Protocol):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    def publish(self, event: CHERENKOVEvent) -> None: ...
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""

    def subscribe(
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        self, event_name: str, handler: Callable[[CHERENKOVEvent], None]
    ) -> None: ...

    def unsubscribe(
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        self, event_name: str, handler: Callable[[CHERENKOVEvent], None]
    ) -> None: ...

    @property
    def handlers(self) -> dict[str, list[Callable[[CHERENKOVEvent], None]]]: ...
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
