from __future__ import annotations

from typing import Protocol

from cherenkov.core.knowledge_result import KnowledgeResult


class KnowledgeRepository(Protocol):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    def store(self, result: KnowledgeResult) -> None: ...
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""

    def get(self, key: str) -> KnowledgeResult | None: ...
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""

    def search(self, query: str, limit: int = 10) -> list[KnowledgeResult]: ...
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""

    def delete(self, key: str) -> bool: ...
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""

    def list_by_kind(self, kind: str, limit: int = 50) -> list[KnowledgeResult]: ...
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
