from __future__ import annotations

from typing import Any, Protocol

from cherenkov.core.events import CHERENKOVEvent


class NotifierPort(Protocol):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    name: str

    def send(self, report: dict[str, Any]) -> bool:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        pass

    def notify_event(self, event: CHERENKOVEvent) -> None:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        pass
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""

class ExporterPort(Protocol):
    """Placeholder docstring.

<description>"""
    name: str

    def export(self, report: dict[str, Any]) -> dict[str, Any]:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        pass
