from __future__ import annotations

from typing import Any, Protocol


class VLMProvider(Protocol):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    def describe_image(self, image_path: str, prompt: str = "") -> str: ...

    def compare_images(
        self, baseline_path: str, actual_path: str
    ) -> dict[str, Any]: ...

    def health(self) -> bool: ...
