"""
cherenkov/cli/core.py — Core entry point and command registration for the CHERENKOV CLI.
"""

from __future__ import annotations

import re
import sys

import click

from cherenkov.cli.tiers import TieredGroup, labs_names

# Google-style API-doc sections. These belong in generated API reference, not in
# `--help`: 43 of 53 commands were rendering blocks like "Args: desktop (bool):
# Parameter desktop. / Returns: None: Command execution result." into the CLI's
# primary discoverability surface, saying nothing a user needs. `Example(s):` is
# deliberately absent — those are worth showing.
_DOCSTRING_SCAFFOLDING = re.compile(
    r"^[ \t]*(?:Args|Arguments|Returns|Raises|Yields|Attributes)[ \t]*:[ \t]*$",
    re.MULTILINE,
)


def _strip_docstring_scaffolding(text: str | None) -> str | None:
    """Trim a help string at the first API-doc section heading.

    Docstrings here put the human summary first and the scaffolding last, so
    truncating at the first heading keeps everything a reader wants and drops
    what the autogenerated-docstring sweep added.
    """
    if not text:
        return text
    match = _DOCSTRING_SCAFFOLDING.search(text)
    if not match:
        return text
    return text[: match.start()].rstrip() or None


def _clean_help_recursively(command: click.Command, _seen: set[int] | None = None) -> None:
    """Apply the trim to a command and every subcommand it exposes."""
    _seen = _seen if _seen is not None else set()
    if id(command) in _seen:  # groups share command objects with top-level aliases
        return
    _seen.add(id(command))
    command.help = _strip_docstring_scaffolding(command.help)
    for sub in getattr(command, "commands", {}).values():
        _clean_help_recursively(sub, _seen)

# Import the plugins command group for registration
from cherenkov.cli.commands.plugins_cmd import plugins_cmd

def _get_version() -> str:
    try:
        from importlib.metadata import version, PackageNotFoundError
        try:
            return version("cherenkov-qa")
        except PackageNotFoundError:
            pass
        try:
            return version("cherenkov")
        except PackageNotFoundError:
            pass
    except ImportError:
        pass
    return "dev"


@click.group(cls=TieredGroup, invoke_without_command=True)
@click.version_option(version=_get_version(), prog_name="cherenkov")
@click.pass_context
def cli(ctx):
    """Cherenkov — the integrity gate for AI-written tests.

    Before you merge an AI agent's change to your tests, prove they still
    catch bugs. Start with: cherenkov demo, then cherenkov check.

Args:
    ctx: Click context object passed by click.pass_context.

Returns:
    None: Command execution result.
    """
    if ctx.invoked_subcommand is None:
        click.echo(ctx.get_help())



def _register_commands() -> None:
    from cherenkov.cli.commands.advanced import (
        hitl_cmd,
        mcp_cmd,
        perf_cmd,
        review_cmd,
        visual_cmd,
    )
    from cherenkov.cli.commands.agent_cmd import agent_cmd
    from cherenkov.cli.commands.plugins_cmd import plugins_cmd
    from cherenkov.cli.commands.audit import audit_cmd
    from cherenkov.cli.commands.bench import bench_cmd
    from cherenkov.cli.commands.brain_cmd import brain_cmd
    from cherenkov.cli.commands.certify import certify_cmd
    from cherenkov.cli.commands.check_stale import check_stale_cmd
    from cherenkov.cli.commands.check_cmd import check_cmd
    from cherenkov.cli.commands.check_suite import check_suite_cmd
    from cherenkov.cli.commands.demo_cmd import demo_cmd
    from cherenkov.cli.commands.docs_cmd import docs_cmd
    from cherenkov.cli.commands.drift_cmd import drift_cmd
    from cherenkov.cli.commands.enterprise import enterprise_cmd
    from cherenkov.cli.commands.epoch import (
        author_cmd,
        daemon_cmd,
        dashboard_cmd,
        explore_cmd,
        governance_cmd,
        map_cmd,
        profile_cmd,
        record_cmd,
        tokens_cmd,
    )
    from cherenkov.cli.commands.eval_cmd import eval_cmd
    from cherenkov.cli.commands.examples_cmd import examples_cmd
    from cherenkov.cli.commands.generate_cmd import generate_cmd
    from cherenkov.cli.commands.guardian_cmd import guardian_cmd
    from cherenkov.cli.commands.ocr_cmd import ocr_cmd
    from cherenkov.cli.commands.playbook_cmd import playbook_cmd
    from cherenkov.cli.commands.routine_cmd import routine_cmd
    from cherenkov.stages.mobile_cmd import mobile as mobile_cmd
    from cherenkov.cli.commands.simple import (
        completion_cmd,
        diff_cmd,
        doctor_cmd,
        eject_cmd,
        init_cmd,
        report_cmd,
        self_test_cmd,
    )
    from cherenkov.cli.commands.teleport_cmd import teleport_cmd
    from cherenkov.cli.commands.train_cmd import train_cmd
    from cherenkov.cli.commands.validate import validate_cmd
    from cherenkov.cli.commands.verify import verify_cmd
    from cherenkov.cli.commands.federation_cmd import federation_cmd
    from cherenkov.cli.commands.template_cmd import template_cmd
    from cherenkov.cli.groups import build_groups
    from cherenkov.synthetic.cmd import synthetic_cmd

    cmd_map: dict[str, click.Command] = {}
    for cmd, name in [
        (audit_cmd, "audit"),
        (verify_cmd, "verify"),
        (labs_cmd, "labs"),
        (check_cmd, "check"),
        (check_suite_cmd, "check-suite"),
        (validate_cmd, "validate"),
        (synthetic_cmd, "synthetic"),
        (diff_cmd, "diff"),
        (report_cmd, "report"),
        (eject_cmd, "eject"),
        (self_test_cmd, "self-test"),
        (completion_cmd, "completion"),
        (init_cmd, "init"),
        (doctor_cmd, "doctor"),
        (visual_cmd, "visual"),
        (perf_cmd, "perf"),
        (mobile_cmd, "mobile"),
        (hitl_cmd, "hitl"),
        (review_cmd, "review"),
        (mcp_cmd, "mcp"),
        (generate_cmd, "generate"),
        (dashboard_cmd, "dashboard"),
        (map_cmd, "map"),
        (daemon_cmd, "daemon"),
        (explore_cmd, "explore"),
        (author_cmd, "author"),
        (record_cmd, "record"),
        (tokens_cmd, "tokens"),
        (governance_cmd, "governance"),
        (certify_cmd, "certify"),
        (profile_cmd, "profile"),
        (bench_cmd, "bench"),
        (brain_cmd, "brain"),
        (ocr_cmd, "ocr"),
        (check_stale_cmd, "check-stale"),
        (drift_cmd, "drift"),
        (demo_cmd, "demo"),
        (eval_cmd, "eval"),
        (examples_cmd, "examples"),
        (docs_cmd, "docs"),
        (agent_cmd, "agent"),
        (plugins_cmd, "plugins"),
        (routine_cmd, "routine"),
        (federation_cmd, "federation"),
        (teleport_cmd, "teleport"),
        (enterprise_cmd, "enterprise"),
        (playbook_cmd, "playbook"),
        (guardian_cmd, "guardian"),
        (template_cmd, "template"),
        (train_cmd, "train"),
    ]:
        cli.add_command(cmd, name=name)
        cmd_map[name] = cmd

    # Register logical command groups (top-level aliases remain for backwards compat)
    for group in build_groups(cmd_map):
        cli.add_command(group)

    # Keep `--help` free of API-doc scaffolding. Done centrally rather than by
    # editing 43 docstrings, so a future autogenerated-docstring pass cannot
    # quietly reintroduce it.
    _clean_help_recursively(cli)


@click.command("labs")
def labs_cmd() -> None:
    """List experimental (Labs) commands.

    They stay fully callable, but are outside the integrity-gate product and
    frozen for new features.
    """
    ctx = click.get_current_context()
    root = ctx.find_root().command
    assert isinstance(root, click.Group)  # the root CLI is always a group
    for name in labs_names(root):
        cmd = root.get_command(ctx, name)
        click.echo(f"  {name:<14} {cmd.get_short_help_str(limit=60) if cmd else ''}")


def main():
    """Main CLI entry point executing legacy command rewriting and Click command invocation.

    Returns:
        None
    """
    # Legacy bare invocation: `cherenkov --spec foo.yaml` → `cherenkov validate --spec foo.yaml`
    if len(sys.argv) > 1 and sys.argv[1].startswith("-") and "--spec" in sys.argv[1:]:
        sys.argv.insert(1, "validate")
    _register_commands()
    cli()


if __name__ == "__main__":
    main()
