"""
CHERENKOV stages/mobile_review.py — Maestro YAML review and integrity gate.

Two kinds of check run here. Structural checks confirm the flow is valid
Maestro. Integrity checks confirm the flow can actually fail: an assertion whose
expected text matches anything (``.*``, ``.+``, ``*``, empty) is a weakened
assertion, and a flow with no assertion at all proves nothing no matter how many
taps it performs. Those are the same failure modes the API-side suite auditor
looks for, applied to mobile flows.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass, field

from cherenkov.stages.mobile_generate import DEFAULT_APP_ID, MobileGenerateOutput

_RE_MAESTRO_CMD = re.compile(
    r"^- (tapOn|inputText|assertVisible|assertNotVisible|waitFor|takeScreenshot|runFlow|scrollUntilVisible)",
    re.MULTILINE,
)
_RE_INDENTED_VALUE = re.compile(r"^\s+text:|^\s+path:|^\s+when:", re.MULTILINE)
_RE_ASSERTION = re.compile(
    r"^- (assertVisible|assertNotVisible):\s*\n\s+text:\s*\"(.*)\"",
    re.MULTILINE,
)

# Expected-text values that match any screen, and so can never fail.
_VACUOUS = {"", ".*", ".+", "*", ".*?", "^.*$", "^.*", ".*$"}


@dataclass
class MobileReviewOutput:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    scenario_id: str
    passed: bool
    errors: list[str] = field(default_factory=list)
    status: str = "ok"
    warnings: list[str] = field(default_factory=list)


class MobileReviewStage:
    """Validates generated Maestro YAML structure, syntax, and assertion strength.

    Args:
        strict: When True, a flow carrying no assertion at all is an error
            rather than a warning. The CLI enables this by default; the
            permissive default keeps the stage usable for structural-only
            checks.
    """

    def __init__(self, run_id: str | None = None, strict: bool = False):
        self.run_id = run_id
        self.strict = strict

    def run(self, generate_output: MobileGenerateOutput) -> MobileReviewOutput:
        """Review one generated flow and return its verdict."""
        t0 = time.monotonic()
        errors: list[str] = []
        warnings: list[str] = []
        yaml_text = generate_output.yaml_content

        if not yaml_text.strip():
            errors.append("Generated YAML is empty")

        if "appId:" not in yaml_text:
            errors.append("Missing required 'appId' field")

        if not _RE_MAESTRO_CMD.search(yaml_text):
            errors.append("No Maestro commands found in generated YAML")

        has_indented_value = bool(_RE_INDENTED_VALUE.search(yaml_text))
        if not has_indented_value:
            errors.append("Commands missing required indented values (text/path/when)")

        # ── Integrity gates ──────────────────────────────────────────────────
        assertions = _RE_ASSERTION.findall(yaml_text)
        for kind, expected in assertions:
            if expected.strip() in _VACUOUS:
                errors.append(
                    f"Weakened assertion: {kind} with expected text "
                    f'"{expected}" matches any screen and can never fail'
                )

        if not assertions and yaml_text.strip():
            message = (
                "Flow contains no assertion — it exercises the app but proves "
                "nothing about it"
            )
            (errors if self.strict else warnings).append(message)

        for step in generate_output.unassertable_steps:
            warnings.append(
                f"Step '{step}' yielded no concrete expected text; "
                "no assertion was emitted for it"
            )

        if f"appId: {DEFAULT_APP_ID}" in yaml_text:
            warnings.append(
                f"Flow targets placeholder appId '{DEFAULT_APP_ID}'; "
                "pass --app-id or plan from a real .apk/.hil source"
            )

        passed = not errors

        dt = int((time.monotonic() - t0) * 1000)
        if self.run_id:
            print(
                f"[MOBILE_REVIEW] stage {'passed' if passed else 'failed'} — {len(errors)} errors — {dt}ms"
            )

        return MobileReviewOutput(
            scenario_id=generate_output.scenario_id,
            passed=passed,
            errors=errors,
            warnings=warnings,
        )
