"""
CHERENKOV stages/mobile_generate.py — Maestro YAML test generator stage.

The assertion text is derived from the planned step, never widened to a
catch-all. `assertVisible: text: ".*"` matches any screen — it is a passing
assertion that proves nothing, which is the weakened-assertion pattern
CHERENKOV exists to catch. When a step yields no concrete expected text the
scenario records an unassertable step instead of emitting a vacuous check.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass, field

from cherenkov.stages.mobile_plan import MobileScenario, MobileStep

DEFAULT_APP_ID = "com.example.app"

# Filler words stripped when turning a free-text step into assertion text.
_FILLER = {"the", "a", "an", "is", "are", "be", "should", "visible", "shown",
           "screen", "for", "to", "that", "and"}

# Instruction verbs that open a verify step. They describe the check, not the
# text on screen, so a leading one is dropped before the filler pass.
_LEADING_VERBS = {"verify", "assert", "expect", "check", "ensure", "confirm", "see"}


@dataclass
class MobileGenerateOutput:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    scenario_id: str
    yaml_content: str
    status: str = "ok"
    app_id: str = DEFAULT_APP_ID
    unassertable_steps: list[str] = field(default_factory=list)


def _assertion_text(raw: str) -> str:
    """Extract concrete expected text from a verify step.

    'verify dashboard visible' -> 'dashboard'. Returns '' when nothing
    substantive survives, which the caller treats as unassertable.
    """
    cleaned = re.sub(r"[^\w\s'-]", " ", raw or "").strip()
    words = cleaned.split()
    if words and words[0].lower() in _LEADING_VERBS:
        words = words[1:]
    words = [w for w in words if w.lower() not in _FILLER]
    return " ".join(words).strip()


class MobileGenerateStage:
    """Produces Maestro-compatible YAML flows from planned mobile scenarios."""

    def __init__(self, run_id: str | None = None, app_id: str | None = None):
        self.run_id = run_id
        self.app_id = app_id

    def _steps_for(self, scenario: MobileScenario) -> list[MobileStep]:
        """Prefer structured planned steps; fall back to parsing free text."""
        if scenario.planned_steps:
            return scenario.planned_steps

        steps: list[MobileStep] = []
        for step in scenario.steps:
            lowered = step.lower()
            if "tap " in lowered:
                steps.append(MobileStep("tap", step[lowered.index("tap ") + 4 :]))
            elif "enter " in lowered:
                steps.append(MobileStep("enter", step[lowered.index("enter ") + 6 :]))
            elif "capture" in lowered:
                steps.append(MobileStep("capture", step))
            elif "verify" in lowered or "visible" in lowered:
                # Drop the leading instruction verb so the step reads back as
                # written ("verify X"), not as "verify verify X".
                words = step.split()
                target = (
                    " ".join(words[1:])
                    if words and words[0].lower() in _LEADING_VERBS
                    else step
                )
                steps.append(
                    MobileStep("verify", target, expected_text=_assertion_text(step))
                )
            elif "launch" in lowered or "wait" in lowered:
                steps.append(MobileStep("wait", step))
            else:
                steps.append(MobileStep("runflow", step))
        return steps

    def run(self, scenario: MobileScenario) -> MobileGenerateOutput:
        """Render one planned scenario into a Maestro flow."""
        t0 = time.monotonic()
        app_id = self.app_id or scenario.app_id or DEFAULT_APP_ID
        unassertable: list[str] = []

        yaml_lines = [f"appId: {app_id}", "---", f"name: {scenario.name}", ""]

        for step in self._steps_for(scenario):
            if step.action == "tap":
                yaml_lines.append("- tapOn:")
                yaml_lines.append(f'    text: "{step.target.strip()}"')
            elif step.action == "enter":
                field_name = step.target.strip().split(" ", 1)[0] or "value"
                yaml_lines.append("- inputText:")
                yaml_lines.append(f'    text: "test_{field_name}"')
            elif step.action in ("launch", "wait"):
                yaml_lines.append("- waitFor: 2")
            elif step.action == "capture":
                step_id = step.as_phrase().lower().replace(" ", "_")
                yaml_lines.append("- takeScreenshot:")
                yaml_lines.append(
                    f'    path: "screenshots/{scenario.id}_{step_id}.png"'
                )
            elif step.action == "verify":
                expected = step.expected_text.strip() or _assertion_text(step.target)
                if not expected:
                    # No concrete text to check — record it rather than emitting
                    # a catch-all assertion that would always pass.
                    unassertable.append(step.as_phrase())
                    continue
                yaml_lines.append("- assertVisible:")
                yaml_lines.append(f'    text: "{expected}"')
            else:
                yaml_lines.append("- runFlow:")
                yaml_lines.append("    when:")
                yaml_lines.append(f'      visible: "{step.target.strip()}"')

        yaml_content = "\n".join(yaml_lines)

        dt = int((time.monotonic() - t0) * 1000)
        if self.run_id:
            print(f"[MOBILE_GENERATE] stage success — {scenario.id} — {dt}ms")
        return MobileGenerateOutput(
            scenario_id=scenario.id,
            yaml_content=yaml_content,
            app_id=app_id,
            unassertable_steps=unassertable,
        )
