"""
CHERENKOV stages/plan.py — deterministic scenario planner.

Deterministic-by-design: maps the mutation menu produced by IngestStage to
Scenario contracts using priority rules. No LLM call is made here.
"""

from __future__ import annotations

import time

from cherenkov.core.contracts import (
    PlanOutput,
    IngestOutput,
    Scenario,
    Status,
    StageMeta,
)
from cherenkov.core.errors import get_logger


class PlanStage:
    """Selects and prioritizes scenarios from the deterministic mutation menu generated by Ingest."""

    def __init__(self, run_id: str | None = None):
        self.log = get_logger("PLAN", run_id)

    def run(self, ingest: IngestOutput) -> PlanOutput:
        t0 = time.time()
        self.log.info("stage start", endpoints_count=len(ingest.endpoints))

        if ingest.status == Status.FAILED:
            self.log.error("upstream ingest failed; propagating failure")
            dt = int((time.time() - t0) * 1000)
            return PlanOutput(
                scenarios=[],
                status=Status.FAILED,
                errors=ingest.errors,
                metadata=StageMeta(stage="PLAN", duration_ms=dt),
            )

        scenarios: list[Scenario] = []

        for ep in ingest.endpoints:
            for mut in ep.mutations:
                # Prioritization: happy path & auth are P1, validation and security mutations are P2
                priority = "P1" if mut.case_type in ("happy_path", "auth") else "P2"

                scenarios.append(
                    Scenario(
                        endpoint=ep.path,
                        method=ep.method,
                        case_type=mut.case_type,
                        priority=priority,
                        mutation_id=mut.id,
                        expected_status=mut.expected_status,
                    )
                )

        dt = int((time.time() - t0) * 1000)
        self.log.info("stage success", scenarios_count=len(scenarios), duration_ms=dt)

        return PlanOutput(
            scenarios=scenarios,
            status=Status.OK,
            metadata=StageMeta(stage="PLAN", duration_ms=dt),
        )
