"""Obsidian vault exporter — the map as a folder of notes you can actually open.

Every node becomes a markdown note with YAML frontmatter and ``[[wikilinks]]``
to its neighbours, so Obsidian's own graph view, backlinks pane, search and
Dataview queries all work on the map with no plugin and no import step. Point
Obsidian at the output directory and it is a vault.

Two properties make the export safe to re-run on a schedule:

*Ownership.* Generated notes carry ``cherenkov_generated: true`` in their
frontmatter and are listed in a manifest at the vault root. A note that is not
in the manifest is never touched, so hand-written notes can live in the same
vault and link into the generated ones.

*Reconciliation.* Notes that were generated by a previous run and no longer
correspond to a node are deleted. Without that step the vault accumulates
ghosts — notes for modules that were deleted months ago — which is exactly the
stale-documentation failure the map exists to prevent.
"""

from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

from cherenkov.brainmap.domain.models import (
    KIND_ADR,
    KIND_CLASS,
    KIND_CLI_COMMAND,
    KIND_COMPONENT,
    KIND_DOC,
    KIND_EXTERNAL,
    KIND_FUNCTION,
    KIND_MODULE,
    KIND_PACKAGE,
    KIND_ROUTE,
    KIND_TEST,
    BrainMap,
    Node,
)

MANIFEST_NAME = ".brainmap-manifest.json"
GENERATED_KEY = "cherenkov_generated"

FOLDERS = {
    KIND_MODULE: "Modules",
    KIND_PACKAGE: "Packages",
    KIND_CLASS: "Symbols",
    KIND_FUNCTION: "Symbols",
    KIND_COMPONENT: "Components",
    KIND_ROUTE: "Routes",
    KIND_CLI_COMMAND: "Commands",
    KIND_DOC: "Docs",
    KIND_ADR: "Decisions",
    KIND_TEST: "Tests",
    KIND_EXTERNAL: "Dependencies",
}

# Edge kind → the sentence introducing that block of links in a note.
EDGE_HEADINGS = {
    "imports": "Imports",
    "contains": "Contains",
    "defines": "Defines",
    "links": "Links to",
    "mentions": "Mentions",
    "tests": "Tests",
    "handled_by": "Handled by",
    "documents": "Documents",
    "calls": "Calls",
}

_UNSAFE = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


class ObsidianVaultExporter:
    """Writes a reconciled map into an Obsidian-compatible vault."""

    name = "obsidian"

    def export(self, map_: BrainMap, target: Path) -> dict[str, Any]:
        """Render the map into ``target`` and prune stale generated notes.

        Args:
            map_ (BrainMap): A reconciled map.
            target (Path): Vault directory; created if missing.

        Returns:
            dict[str, Any]: Counts of notes written, removed and kept.
        """
        target = Path(target)
        target.mkdir(parents=True, exist_ok=True)
        previous = _read_manifest(target)

        names = _assign_names(map_)
        outgoing, incoming = _adjacency(map_)

        written: dict[str, str] = {}
        for node in map_.nodes.values():
            rel = f"{FOLDERS.get(node.kind, 'Nodes')}/{names[node.id]}.md"
            path = target / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                _render_note(node, names, outgoing.get(node.id, []), incoming.get(node.id, []), map_),
                encoding="utf-8",
            )
            written[node.id] = rel

        index_files = _write_indexes(target, map_, names)
        canvas = _write_canvas(target, map_, names, outgoing)

        stale = _prune(target, previous, set(written.values()) | index_files | {canvas})
        _write_manifest(target, map_, written, index_files | {canvas})
        return {
            "vault": str(target),
            "notes_written": len(written),
            "index_notes": len(index_files) + 1,
            "stale_removed": stale,
            "nodes": len(map_.nodes),
        }


# ── naming ──────────────────────────────────────────────────────────────────
def _safe_name(text: str) -> str:
    """Turn a node title into a filename Obsidian and every OS will accept."""
    cleaned = _UNSAFE.sub("-", text)
    # A route title is ``GET /api/v1/runs``; naive substitution leaves
    # ``GET -api-v1-runs``, so collapse the artefacts the substitution creates
    # rather than shipping filenames with stray separators.
    cleaned = re.sub(r"\s+-+", " ", cleaned)
    cleaned = re.sub(r"-{2,}", "-", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip().strip(".-")
    return (cleaned or "untitled")[:120]


def _assign_names(map_: BrainMap) -> dict[str, str]:
    """Return node id → unique note name.

    Obsidian resolves ``[[wikilinks]]`` by filename, so names must be unique
    across the whole vault. Collisions are broken by appending the node kind,
    then a counter — deterministically, so a rebuild produces the same names
    and the vault's own git history stays readable.

    Args:
        map_ (BrainMap): The map being exported.

    Returns:
        dict[str, str]: Node id → note name (no extension).
    """
    names: dict[str, str] = {}
    used: dict[str, int] = {}
    for node in sorted(map_.nodes.values(), key=lambda n: (n.kind, n.id)):
        base = _safe_name(node.title)
        candidate = base
        if candidate.lower() in used:
            candidate = _safe_name(f"{node.title} ({node.kind})")
        while candidate.lower() in used:
            used[candidate.lower()] += 1
            candidate = _safe_name(f"{node.title} ({node.kind} {used[candidate.lower()]})")
        used[candidate.lower()] = 1
        names[node.id] = candidate
    return names


def _adjacency(map_: BrainMap) -> tuple[dict[str, list], dict[str, list]]:
    """Return outgoing and incoming edge lists keyed by node id."""
    outgoing: dict[str, list] = defaultdict(list)
    incoming: dict[str, list] = defaultdict(list)
    for edge in map_.edges:
        if not edge.dst:
            continue
        outgoing[edge.src].append(edge)
        incoming[edge.dst].append(edge)
    return outgoing, incoming


# ── rendering ───────────────────────────────────────────────────────────────
def _render_note(node: Node, names: dict[str, str], out_edges: list, in_edges: list, map_: BrainMap) -> str:
    """Render one node as a markdown note.

    Args:
        node (Node): The node to render.
        names (dict[str, str]): Node id → note name.
        out_edges (list): Edges leaving this node.
        in_edges (list): Edges entering this node.
        map_ (BrainMap): The map, for finding lookups.

    Returns:
        str: Full note text, frontmatter included.
    """
    lines = ["---"]
    lines.append(f"{GENERATED_KEY}: true")
    lines.append(f"id: {json.dumps(node.id)}")
    lines.append(f"kind: {node.kind}")
    if node.layer:
        lines.append(f"layer: {node.layer}")
    if node.origin:
        lines.append(f"source: {json.dumps(node.origin)}")
    lines.append(f"weight: {node.weight:g}")
    if node.tags:
        lines.append("tags:")
        lines.extend(f"  - {tag}" for tag in node.tags)
    lines.append("---")
    lines.append("")
    lines.append(f"# {node.title}")
    lines.append("")
    if node.summary:
        lines.append(f"> {node.summary}")
        lines.append("")
    if node.origin:
        lines.append(f"**Source:** `{node.origin}`")
        lines.append("")

    interesting = {k: v for k, v in node.attrs.items() if k not in ("path", "exports") and v not in ("", [], {})}
    if interesting:
        lines.append("| field | value |")
        lines.append("| --- | --- |")
        for key in sorted(interesting):
            value = interesting[key]
            rendered = ", ".join(map(str, value)) if isinstance(value, list) else str(value)
            cell = _cell(rendered)
            lines.append(f"| {key} | {cell} |")
        lines.append("")

    lines.extend(_link_block("Outgoing", out_edges, names, "dst"))
    lines.extend(_link_block("Incoming", in_edges, names, "src"))

    node_findings = [f for f in map_.findings if f.node_id == node.id]
    if node_findings:
        lines.append("## Findings")
        lines.append("")
        for finding in node_findings:
            lines.append(f"- `{finding.severity}` **{finding.code}** — {finding.message}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by `cherenkov brain export`. Edits here are overwritten on the next sync.*")
    return "\n".join(lines) + "\n"


def _cell(text: str, limit: int = 200) -> str:
    """Escape a value so it cannot break out of a markdown table cell."""
    return text[:limit].replace("|", r"\|").replace("\n", " ")


def _link_block(heading: str, edges: list, names: dict[str, str], side: str) -> list[str]:
    """Render one direction's links, grouped by edge kind."""
    if not edges:
        return []
    grouped: dict[str, list[str]] = defaultdict(list)
    for edge in edges:
        target = getattr(edge, side)
        name = names.get(target)
        if name and name not in grouped[edge.kind]:
            grouped[edge.kind].append(name)
    if not any(grouped.values()):
        return []
    lines = [f"## {heading}", ""]
    for kind in sorted(grouped):
        label = EDGE_HEADINGS.get(kind, kind.replace("_", " ").title())
        links = ", ".join(f"[[{name}]]" for name in sorted(grouped[kind]))
        lines.append(f"- **{label}:** {links}")
    lines.append("")
    return lines


def _write_indexes(target: Path, map_: BrainMap, names: dict[str, str]) -> set[str]:
    """Write the home note, per-kind indexes and the findings note.

    Args:
        target (Path): Vault root.
        map_ (BrainMap): The map being exported.
        names (dict[str, str]): Node id → note name.

    Returns:
        set[str]: Vault-relative paths of the notes written.
    """
    stats = map_.stats()
    written: set[str] = set()
    by_kind: dict[str, list[Node]] = defaultdict(list)
    for node in map_.nodes.values():
        by_kind[node.kind].append(node)

    home = [
        "---",
        f"{GENERATED_KEY}: true",
        "kind: index",
        "---",
        "",
        f"# {map_.project} — Brain Map",
        "",
        f"*{stats['nodes']} nodes · {stats['edges']} edges · {stats['files']} files · built {map_.built_at}*",
        "",
        "## Contents",
        "",
    ]
    for kind in sorted(by_kind):
        folder = FOLDERS.get(kind, "Nodes")
        home.append(f"- **{kind}** ({len(by_kind[kind])}) → [[{folder} Index]]")
    home += ["", "## Health", ""]
    severities = stats.get("by_severity", {})
    if severities:
        for severity in ("error", "warn", "info"):
            if severities.get(severity):
                home.append(f"- `{severity}`: {severities[severity]}")
        home.append("")
        home.append("See [[Findings]].")
    else:
        home.append("No findings — every reference in this map resolves.")
    home += ["", "## Most connected", ""]
    degree = map_.degree()
    for node_id, count in sorted(degree.items(), key=lambda kv: (-kv[1], kv[0]))[:20]:
        if node_id in names:
            home.append(f"- [[{names[node_id]}]] — {count}")
    (target / "Brain Map.md").write_text("\n".join(home) + "\n", encoding="utf-8")
    written.add("Brain Map.md")

    for kind, nodes in by_kind.items():
        folder = FOLDERS.get(kind, "Nodes")
        rel = f"{folder}/{folder} Index.md"
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        body = [
            "---",
            f"{GENERATED_KEY}: true",
            "kind: index",
            "---",
            "",
            f"# {folder} Index",
            "",
            f"{len(nodes)} {kind} nodes.",
            "",
        ]
        for node in sorted(nodes, key=lambda n: n.title.lower()):
            suffix = f" — {node.summary}" if node.summary else ""
            body.append(f"- [[{names[node.id]}]]{suffix}")
        path.write_text("\n".join(body) + "\n", encoding="utf-8")
        written.add(rel)

    findings = [
        "---",
        f"{GENERATED_KEY}: true",
        "kind: report",
        "---",
        "",
        "# Findings",
        "",
        "What reconciliation could not make sense of, worst first.",
        "",
    ]
    if map_.findings:
        findings += ["| severity | code | where | detail |", "| --- | --- | --- | --- |"]
        for finding in map_.findings[:500]:
            where = names.get(finding.node_id or "", finding.origin or "")
            link = f"[[{where}]]" if finding.node_id in names else f"`{where}`"
            message = _cell(finding.message)
            findings.append(f"| {finding.severity} | {finding.code} | {link} | {message} |")
        if len(map_.findings) > 500:
            findings.append("")
            findings.append(f"*…and {len(map_.findings) - 500} more.*")
    else:
        findings.append("None.")
    (target / "Findings.md").write_text("\n".join(findings) + "\n", encoding="utf-8")
    written.add("Findings.md")
    return written


def _write_canvas(target: Path, map_: BrainMap, names: dict[str, str], outgoing: dict[str, list]) -> str:
    """Write a JSON Canvas of the most connected nodes.

    Obsidian opens ``.canvas`` files natively, so the highest-signal slice of
    the map gets a spatial layout rather than only a note list. Only the top
    hubs are laid out: a canvas of ten thousand cards helps nobody.

    Args:
        target (Path): Vault root.
        map_ (BrainMap): The map being exported.
        names (dict[str, str]): Node id → note name.
        outgoing (dict[str, list]): Outgoing edges by node id.

    Returns:
        str: Vault-relative path of the canvas file.
    """
    degree = map_.degree()
    top = [node_id for node_id, _ in sorted(degree.items(), key=lambda kv: (-kv[1], kv[0]))[:40]]
    index = {node_id: position for position, node_id in enumerate(top)}
    columns = 8
    cards = []
    for node_id in top:
        position = index[node_id]
        cards.append(
            {
                "id": f"n{position}",
                "type": "file",
                "file": f"{FOLDERS.get(map_.nodes[node_id].kind, 'Nodes')}/{names[node_id]}.md",
                "x": (position % columns) * 420,
                "y": (position // columns) * 260,
                "width": 380,
                "height": 200,
            }
        )
    links: list[dict[str, Any]] = []
    for node_id in top:
        for edge in outgoing.get(node_id, []):
            if edge.dst in index:
                links.append(
                    {
                        "id": f"e{len(links)}",
                        "fromNode": f"n{index[node_id]}",
                        "fromSide": "right",
                        "toNode": f"n{index[edge.dst]}",
                        "toSide": "left",
                        "label": edge.kind,
                    }
                )
    (target / "Brain Map.canvas").write_text(
        json.dumps({"nodes": cards, "edges": links}, indent=2), encoding="utf-8"
    )
    return "Brain Map.canvas"


# ── manifest & pruning ──────────────────────────────────────────────────────
def _read_manifest(target: Path) -> dict[str, Any]:
    """Read the previous export manifest, or an empty one."""
    path = target / MANIFEST_NAME
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def _write_manifest(target: Path, map_: BrainMap, notes: dict[str, str], extras: set[str]) -> None:
    """Record what this run generated, so the next run can prune it."""
    payload = {
        "project": map_.project,
        "built_at": map_.built_at,
        "notes": notes,
        "extras": sorted(extras),
    }
    (target / MANIFEST_NAME).write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")


def _prune(target: Path, previous: dict[str, Any], current: set[str]) -> int:
    """Delete notes this exporter generated before and no longer produces.

    A file is removed only if the previous manifest claims it *and* it still
    carries the generated marker: if someone adopted a generated note by
    editing out the marker, their note survives.

    Args:
        target (Path): Vault root.
        previous (dict[str, Any]): The previous manifest.
        current (set[str]): Vault-relative paths written by this run.

    Returns:
        int: Number of notes deleted.
    """
    was: set[str] = set(previous.get("notes", {}).values()) | set(previous.get("extras", []))
    removed = 0
    for rel in sorted(was - current):
        path = target / rel
        if not path.is_file():
            continue
        if path.suffix == ".md":
            try:
                head = path.read_text(encoding="utf-8")[:400]
            except OSError:
                continue
            if GENERATED_KEY not in head:
                continue
        try:
            path.unlink()
            removed += 1
        except OSError:
            continue
    _prune_empty_dirs(target)
    return removed


def _prune_empty_dirs(target: Path) -> None:
    """Remove directories left empty by pruning."""
    for path in sorted(target.rglob("*"), key=lambda p: len(p.parts), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            try:
                path.rmdir()
            except OSError:
                continue
