from __future__ import annotations

from cherenkov.core.contracts import AccountingReport, CacheStats
from cherenkov.core.settings import get_settings
from cherenkov.substrate.interfaces import CachedInferenceClient, InferenceClient

_current_client: CachedInferenceClient | None = None
_current_provider: str | None = None

def get_client() -> InferenceClient:
    """Return the configured provider client based on get_settings().PROVIDER."""
    global _current_client, _current_provider
    provider = get_settings().PROVIDER.lower().strip()

    if _current_client is not None and _current_provider == provider:
        return _current_client

    raw_client: InferenceClient
    if provider == "ollama":
        from cherenkov.substrate.providers.ollama_client import OllamaInferenceClient
        raw_client = OllamaInferenceClient()
    elif provider == "openai":
        from cherenkov.substrate.providers.openai_client import OpenAIInferenceClient
        raw_client = OpenAIInferenceClient()
    elif provider == "nemoclaw":
        from cherenkov.substrate.providers.nemoclaw_client import NemoClawInferenceClient
        raw_client = NemoClawInferenceClient()
    elif provider == "anthropic":
        from cherenkov.substrate.providers.anthropic_client import AnthropicInferenceClient
        raw_client = AnthropicInferenceClient()
    elif provider == "airllm":
        from cherenkov.substrate.providers.airllm_client import AirLLMInferenceClient
        raw_client = AirLLMInferenceClient()
    else:
        raise ValueError(
            f"Unknown provider '{provider}'. Expected 'ollama', 'openai', 'nemoclaw', 'anthropic', or 'airllm'."
        )

    _current_client = CachedInferenceClient(raw_client)
    _current_provider = provider
    return _current_client

def set_client(client: CachedInferenceClient | None) -> None:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    global _current_client, _current_provider
    _current_client = client
    _current_provider = None

def reset_client() -> None:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    global _current_client, _current_provider
    _current_client = None
    _current_provider = None

def get_accounting_report() -> AccountingReport | None:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    if _current_client is not None:
        return _current_client.accounting_report
    return None

def get_cache_stats() -> CacheStats | None:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    if _current_client is not None:
        return _current_client.cache_stats
    return None
