from __future__ import annotations

from cherenkov.execution.failure_classifier import FailureCategory, classify_failure

_CORPUS = [
    {
        "id": "D-01",
        "endpoint": "GET /pet/findByStatus",
        "claimA": "schema: enum [available, pending, sold]",
        "claimB": "accepts arbitrary status strings",
        "reproSteps": 'curl "https://example.test/pet/findByStatus?status=bogus"',
        "confidence": 0.95,
    },
    {
        "id": "D-02",
        "endpoint": "POST /pet",
        "claimA": "required: [name, photoUrls]",
        "claimB": "accepts missing photoUrls",
        "reproSteps": 'curl -X POST "https://example.test/pet"',
        "confidence": 0.99,
    },
]


def test_matching_endpoint_classifies_as_product_bug():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    result = classify_failure("/pet/findByStatus", "GET", divergences=_CORPUS)
    assert result.category == FailureCategory.PRODUCT_BUG
    assert result.divergence_id == "D-01"
    assert result.confidence == 0.95
    assert result.expected == "schema: enum [available, pending, sold]"
    assert result.actual == "accepts arbitrary status strings"
    assert result.repro is not None and "curl" in result.repro


def test_method_matching_is_case_insensitive_and_normalizes():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    result = classify_failure("/pet", "post", divergences=_CORPUS)
    assert result.category == FailureCategory.PRODUCT_BUG
    assert result.divergence_id == "D-02"
    assert result.method == "POST"


def test_no_correlating_divergence_is_unknown_not_guessed():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    result = classify_failure("/store/order", "DELETE", divergences=_CORPUS)
    assert result.category == FailureCategory.UNKNOWN
    assert result.divergence_id is None
    assert result.confidence is None
    assert "not built yet" in result.reason


def test_wrong_method_on_known_endpoint_does_not_match():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    result = classify_failure("/pet", "DELETE", divergences=_CORPUS)
    assert result.category == FailureCategory.UNKNOWN


def test_defaults_to_demo_corpus_when_no_findings_are_stored(monkeypatch):
    """Fresh install: nothing persisted, so the demo corpus is what's live.

    Since #903 the default source is real persisted findings, and the corpus is
    only the fallback — so pin the empty-store condition rather than depending
    on whether an earlier test in the session happened to run `verify`.
    """
    from cherenkov.web import divergences as div_mod

    monkeypatch.setattr(div_mod, "_stored_divergences", lambda: [])
    result = classify_failure("/pet/findByStatus", "GET")
    assert result.category == FailureCategory.PRODUCT_BUG
    assert result.divergence_id == "D-01"


def test_defaults_to_real_findings_when_they_exist(monkeypatch):
    """Once a real run has produced findings, those supersede the demo corpus."""
    from cherenkov.web import divergences as div_mod

    monkeypatch.setattr(
        div_mod,
        "_stored_divergences",
        lambda: [{
            "id": "run-a:DIV-9", "divergenceClass": "D1", "endpoint": "POST /users",
            "severity": "high", "status": "reproduced", "claimA": "spec says 422",
            "claimB": "server returns 400", "evidence": "e", "reproSteps": "s",
        }],
    )
    # The Petstore demo endpoint is no longer known...
    assert classify_failure("/pet/findByStatus", "GET").category == FailureCategory.UNKNOWN
    # ...but the real one is.
    real = classify_failure("/users", "POST")
    assert real.category == FailureCategory.PRODUCT_BUG
    assert real.divergence_id == "run-a:DIV-9"
