import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "scripts"))

def test_skill_sync_import():
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    try:
        import skill_sync  # noqa: F401
        assert True
    except ImportError:
        pytest.fail("Could not import skill_sync")
