"""Tests for cherenkov/verdict/traffic_capture.py — TrafficCapture."""

from __future__ import annotations

import json
import socket
import threading
import urllib.error
import urllib.request
import uuid
from collections.abc import Generator
from contextlib import contextmanager
from http.server import BaseHTTPRequestHandler, HTTPServer
from typing import Any, ClassVar
from unittest.mock import MagicMock

from cherenkov.core.contracts import (
    DivergenceClass,
    DivergenceEvidence,
    DivergenceHypothesis,
    ReproductionResult,
    Severity,
)
from cherenkov.verdict.traffic_capture import (
    CapturedInteraction,
    CapturingWitnessAgent,
    RecordingProxy,
    TrafficCapture,
    TrafficCaptureReport,
)


def _make_hypothesis() -> DivergenceHypothesis:
    return DivergenceHypothesis(
        id=str(uuid.uuid4()),
        divergence_class=DivergenceClass.D1_SPEC_CODE,
        claim_a="spec says X",
        claim_b="impl does Y",
        predicted_evidence="signal",
        severity=Severity.LOW,
        endpoint="GET /test",
        repro_steps=["Send GET /test", "Expect 200"],
    )


def _make_evidence(status: str = "200", diff: str = "") -> DivergenceEvidence:
    return DivergenceEvidence(
        request_summary=f"GET http://test/test → {status} (10ms)",
        response_actual={"ok": True},
        response_expected={"ok": True},
        diff=diff,
    )


# ── CapturedInteraction ───────────────────────────────────────────────────────

class TestCapturedInteraction:
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    def test_id_auto_generated(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        i = CapturedInteraction()
        assert i.id

    def test_to_fixture_roundtrip(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        i = CapturedInteraction(
            method="GET",
            url="http://test/pet",
            response_status=200,
            response_body={"id": 1},
            spec_conformant=True,
            hypothesis_id="abc",
        )
        fixture = i.to_fixture()
        assert fixture["method"] == "GET"
        assert fixture["spec_conformant"] is True
        assert "captured_at" in fixture


# ── CapturingWitnessAgent._record ─────────────────────────────────────────────
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""

class TestCapturingWitnessAgent:
    def test_record_conformant_when_not_reproduced(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        agent = CapturingWitnessAgent.__new__(CapturingWitnessAgent)
        agent.base_url = "http://test"
        agent.interactions = []

        h = _make_hypothesis()
        ev = _make_evidence(diff="")
        result = ReproductionResult(
            hypothesis_id=h.id, reproduced=False, evidence=ev
        )
        agent._record(h, result)
        assert len(agent.interactions) == 1
        assert agent.interactions[0].spec_conformant is True

    def test_record_not_conformant_when_reproduced(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        agent = CapturingWitnessAgent.__new__(CapturingWitnessAgent)
        agent.base_url = "http://test"
        agent.interactions = []

        h = _make_hypothesis()
        ev = _make_evidence(diff="status mismatch: expected=400, actual=200")
        result = ReproductionResult(
            hypothesis_id=h.id, reproduced=True, evidence=ev
        )
        agent._record(h, result)
        assert agent.interactions[0].spec_conformant is False

    def test_record_no_evidence_skips(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        agent = CapturingWitnessAgent.__new__(CapturingWitnessAgent)
        agent.base_url = "http://test"
        agent.interactions = []

        h = _make_hypothesis()
        result = ReproductionResult(hypothesis_id=h.id, reproduced=False, evidence=None)
        agent._record(h, result)
        assert len(agent.interactions) == 0

    def test_dump_fixtures_writes_only_golden(self, tmp_path):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        agent = CapturingWitnessAgent.__new__(CapturingWitnessAgent)
        agent.base_url = "http://test"
        agent.interactions = [
            CapturedInteraction(spec_conformant=True),
            CapturedInteraction(spec_conformant=False),
            CapturedInteraction(spec_conformant=True),
        ]
        out = tmp_path / "fixtures.jsonl"
        count = agent.dump_fixtures(out)
        assert count == 2
        lines = out.read_text().strip().split("\n")
        assert len(lines) == 2
        for line in lines:
            data = json.loads(line)
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
            assert data["spec_conformant"] is True


# ── TrafficCapture ─────────────────────────────────────────────────────────────

class TestTrafficCapture:
    def test_run_returns_report(self, tmp_path):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        capture = TrafficCapture.__new__(TrafficCapture)
        capture.base_url = "http://test"

        mock_agent = MagicMock(spec=CapturingWitnessAgent)
        mock_agent.interactions = [CapturedInteraction(spec_conformant=True)]
        mock_agent.dump_fixtures.return_value = 1
        capture.agent = mock_agent

        h = _make_hypothesis()
        report = capture.run([h], fixture_dir=tmp_path)
        assert isinstance(report, TrafficCaptureReport)

    def test_replay_loads_fixtures(self, tmp_path):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        fixture_file = tmp_path / "test.jsonl"
        records = [
            {"id": "1", "method": "GET", "url": "http://test", "spec_conformant": True},
            {"id": "2", "method": "POST", "url": "http://test/pet", "spec_conformant": True},
        ]
        with fixture_file.open("w") as f:
            for r in records:
                f.write(json.dumps(r) + "\n")

        capture = TrafficCapture.__new__(TrafficCapture)
        loaded = capture.replay(fixture_file)
        assert len(loaded) == 2
        assert loaded[0]["id"] == "1"

    def test_replay_missing_file_returns_empty(self, tmp_path):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        capture = TrafficCapture.__new__(TrafficCapture)
        result = capture.replay(tmp_path / "nonexistent.jsonl")
        assert result == []

    def test_total_property(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        report = TrafficCaptureReport(
            interactions=[CapturedInteraction(), CapturedInteraction()],
            golden_count=1,
        )
        assert report.total == 2


# ── RecordingProxy — the record half of record-then-perturb ───────────────────


class _FakeTarget(BaseHTTPRequestHandler):
    """Stands in for a user's live API."""

    ROUTES: ClassVar[dict[str, tuple[int, dict]]] = {
        "/orders/42": (200, {"id": 42, "total": 99.5, "status": "paid"}),
        "/orders/7": (200, {"id": 7, "total": 1.0, "status": "pending"}),
        "/forbidden": (403, {"error": "nope"}),
    }

    def _reply(self) -> None:
        status, body = self.ROUTES.get(self.path, (404, {"error": "not found"}))
        raw = json.dumps(body).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    do_GET = _reply
    do_POST = _reply

    def log_message(self, *_: object) -> None:
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        pass


@contextmanager
def _target() -> Generator[str, None, None]:
    srv = HTTPServer(("127.0.0.1", 0), _FakeTarget)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    try:
        yield f"http://127.0.0.1:{srv.server_port}"
    finally:
        srv.shutdown()


def _free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return int(s.getsockname()[1])


def _get(url: str) -> tuple[int, Any]:
    try:
        with urllib.request.urlopen(url, timeout=10) as resp:
            return resp.status, json.loads(resp.read())
    except urllib.error.HTTPError as exc:
        return exc.code, json.loads(exc.read())


class TestRecordingProxy:
    """A spec constrains types, not instance values, so a baseline-free audit
    must perturb the response the target ACTUALLY returned. This records it.
    """

    def test_forwards_the_targets_response_unchanged(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        with _target() as target, RecordingProxy(_free_port(), target) as proxy:
            status, body = _get(f"{proxy.url}/orders/42")
        assert status == 200
        assert body == {"id": 42, "total": 99.5, "status": "paid"}

    def test_records_the_interaction(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        with _target() as target, RecordingProxy(_free_port(), target) as proxy:
            _get(f"{proxy.url}/orders/42")
            interactions = list(proxy.interactions)
        assert len(interactions) == 1
        rec = interactions[0]
        assert rec.method == "GET"
        assert rec.url == "/orders/42"
        assert rec.response_status == 200
        assert rec.response_body["total"] == 99.5

    def test_recorded_base_is_ready_for_the_battery(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        with _target() as target, RecordingProxy(_free_port(), target) as proxy:
            _get(f"{proxy.url}/orders/42")
            base = proxy.recorded_base("/orders/42")
        assert base == (200, {"id": 42, "total": 99.5, "status": "paid"})

    def test_recorded_base_is_none_for_an_unseen_path(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        with _target() as target, RecordingProxy(_free_port(), target) as proxy:
            _get(f"{proxy.url}/orders/42")
            assert proxy.recorded_base("/never/called") is None

    def test_recorded_base_prefers_the_most_recent_response(self):
        """A suite that mutates state should be perturbed against the response
        its assertions were most recently written against."""
        with _target() as target, RecordingProxy(_free_port(), target) as proxy:
            _get(f"{proxy.url}/orders/42")
            _get(f"{proxy.url}/orders/7")
            _get(f"{proxy.url}/orders/42")
            proxy.interactions[-1].response_body = {"id": 42, "total": 0.0, "status": "paid"}
            base = proxy.recorded_base("/orders/42")
        assert base is not None
        assert base[1]["total"] == 0.0

    def test_records_a_4xx_as_a_real_answer(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        with _target() as target, RecordingProxy(_free_port(), target) as proxy:
            status, _ = _get(f"{proxy.url}/forbidden")
            recorded = proxy.recorded_base("/forbidden")
        assert status == 403
        assert recorded is not None and recorded[0] == 403

    def test_replay_map_covers_every_recorded_path(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        with _target() as target, RecordingProxy(_free_port(), target) as proxy:
            _get(f"{proxy.url}/orders/42")
            _get(f"{proxy.url}/orders/7")
            mapping = proxy.replay_map()
        assert set(mapping) == {"/orders/42", "/orders/7"}
        assert mapping["/orders/7"][0] == 200

    def test_unreachable_target_records_502_rather_than_raising(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        dead = f"http://127.0.0.1:{_free_port()}"
        with RecordingProxy(_free_port(), dead) as proxy:
            status, _ = _get(f"{proxy.url}/orders/42")
            recorded = proxy.recorded_base("/orders/42")
        assert status == 502
        assert recorded is not None and recorded[0] == 502
