"""Unit tests for cherenkov/execution/eject.py — EjectorEngine."""

import json
import os
import tempfile
import unittest


class TestSpecFilesIn(unittest.TestCase):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    def _call(self, directory: str) -> list:
        from cherenkov.execution.eject import EjectorEngine

        return EjectorEngine._spec_files_in(directory)

    def test_nonexistent_dir_returns_empty(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        self.assertEqual(self._call("/no/such/path"), [])

    def test_empty_dir_returns_empty(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        with tempfile.TemporaryDirectory() as d:
            self.assertEqual(self._call(d), [])

    def test_spec_ts_file_included(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        with tempfile.TemporaryDirectory() as d:
            path = os.path.join(d, "happy_path.spec.ts")
            with open(path, "w") as f:
                f.write("test content")
            result = self._call(d)
            self.assertIn("happy_path.spec.ts", result)

    def test_empty_spec_file_excluded(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        with tempfile.TemporaryDirectory() as d:
            path = os.path.join(d, "empty.spec.ts")
            open(path, "w").close()
            self.assertEqual(self._call(d), [])

    def test_scores_json_included(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        with tempfile.TemporaryDirectory() as d:
            path = os.path.join(d, "_scores.json")
            with open(path, "w") as f:
                f.write("{}")
            self.assertIn("_scores.json", self._call(d))

    def test_non_spec_files_excluded(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        with tempfile.TemporaryDirectory() as d:
            for name in ("readme.md", "config.json", "test.ts"):
                with open(os.path.join(d, name), "w") as f:
                    f.write("data")
            self.assertEqual(self._call(d), [])


class TestEjectSuite(unittest.TestCase):
    def setUp(self):
        from cherenkov.execution.eject import EjectorEngine

        # allow_packaged_fixtures is the opt-in that keeps this path exercisable
        # without a generated suite present. A real user never gets it.
        self.engine = EjectorEngine(run_id="test-run", allow_packaged_fixtures=True)

    def test_eject_creates_expected_files(self):
        with tempfile.TemporaryDirectory() as base:
            out = os.path.join(base, "ejected")
            result = self.engine.eject_suite(out)
            self.assertTrue(result)
            self.assertTrue(os.path.exists(os.path.join(out, "playwright.config.ts")))
            self.assertTrue(os.path.exists(os.path.join(out, "package.json")))
            self.assertTrue(os.path.exists(os.path.join(out, "client.ts")))
            self.assertTrue(os.path.exists(os.path.join(out, "tsconfig.json")))

    def test_eject_package_json_has_playwright_dep(self):
        with tempfile.TemporaryDirectory() as base:
            out = os.path.join(base, "ejected")
            self.engine.eject_suite(out)
            pkg = json.loads(open(os.path.join(out, "package.json")).read())  # noqa: SIM115
            self.assertIn("@playwright/test", pkg["devDependencies"])

    def test_eject_cleans_existing_output_dir(self):
        with tempfile.TemporaryDirectory() as base:
            out = os.path.join(base, "ejected")
            os.makedirs(out)
            stale = os.path.join(out, "stale.txt")
            with open(stale, "w") as f:
                f.write("old")
            self.engine.eject_suite(out)
            self.assertFalse(os.path.exists(stale))

    def test_eject_client_ts_has_no_cherenkov_trace(self):
        with tempfile.TemporaryDirectory() as base:
            out = os.path.join(base, "ejected")
            self.engine.eject_suite(out)
            content = open(os.path.join(out, "client.ts")).read()  # noqa: SIM115
            self.assertNotIn("cherenkov", content.lower())


class TestEjectCustomTestsDir(unittest.TestCase):
    """Regression: eject hardcoded stub/generated_tests and ignored any custom
    --output-dir `cherenkov generate` was given, silently ejecting unrelated
    tracked fixtures instead of the user's own generated tests while still
    reporting success. `tests_src_dir` lets a caller point eject at wherever
    generate actually wrote its output."""

    def test_custom_tests_src_dir_is_used_instead_of_default(self):
        from cherenkov.execution.eject import EjectorEngine

        with tempfile.TemporaryDirectory() as custom_src, tempfile.TemporaryDirectory() as base:
            spec_path = os.path.join(custom_src, "my_own_scenario.spec.ts")
            with open(spec_path, "w") as f:
                f.write("import { test, expect } from '@playwright/test';\n")

            engine = EjectorEngine(run_id="test-run", tests_src_dir=custom_src)
            self.assertEqual(engine.tests_src_dir, custom_src)

            out = os.path.join(base, "ejected")
            result = engine.eject_suite(out)

            self.assertTrue(result)
            ejected_file = os.path.join(out, "tests", "my_own_scenario.spec.ts")
            self.assertTrue(
                os.path.exists(ejected_file),
                "eject must read from the custom tests_src_dir, not the hardcoded default",
            )

    def test_default_tests_src_dir_resolves_against_cwd_not_the_package(self):
        """The default must match `generate --output-dir`'s default.

        This assertion used to read `os.path.join(default_engine.stub_dir, ...)`
        — i.e. it pinned the defect in place. `generate --output-dir` defaults to
        the relative "stub/generated_tests", resolved against the user's cwd,
        while eject resolved the same name against the installed package. The
        two commands therefore addressed different directories, and the natural
        generate -> eject flow silently ejected CHERENKOV's own fixtures.
        """
        from cherenkov.execution.eject import EjectorEngine

        with tempfile.TemporaryDirectory() as cwd:
            prev = os.getcwd()
            os.chdir(cwd)
            try:
                default_engine = EjectorEngine(run_id="test-run")
                self.assertEqual(
                    default_engine.tests_src_dir,
                    os.path.join(os.getcwd(), "stub", "generated_tests"),
                )
                self.assertFalse(
                    default_engine._is_inside_package(default_engine.tests_src_dir),
                    "the default source must not resolve inside the installed package",
                )
            finally:
                os.chdir(prev)

    def test_cli_eject_tests_dir_flag_is_wired_through(self):
        """End-to-end: `cherenkov eject --tests-dir <custom>` (the CLI flag,
        not just the engine constructor) must actually read from <custom>,
        matching the documented `generate --output-dir <custom>` combo in
        docs/GETTING_STARTED.md."""
        from click.testing import CliRunner

        from cherenkov.cli.commands.simple import eject_cmd

        with tempfile.TemporaryDirectory() as custom_src, tempfile.TemporaryDirectory() as base:
            spec_path = os.path.join(custom_src, "my_own_scenario.spec.ts")
            with open(spec_path, "w") as f:
                f.write("import { test, expect } from '@playwright/test';\n")

            out = os.path.join(base, "ejected")
            runner = CliRunner()
            result = runner.invoke(
                eject_cmd, ["--output", out, "--tests-dir", custom_src]
            )

            self.assertEqual(result.exit_code, 0, result.output)
            ejected_file = os.path.join(out, "tests", "my_own_scenario.spec.ts")
            self.assertTrue(
                os.path.exists(ejected_file),
                "CLI --tests-dir flag must be threaded through to EjectorEngine",
            )
            self.assertIn(custom_src, result.output)

    def test_cli_eject_rejects_nonexistent_tests_dir(self):
        """A typo'd --tests-dir should fail loudly, not silently fall back to
        unrelated tracked fixtures."""
        from click.testing import CliRunner

        from cherenkov.cli.commands.simple import eject_cmd

        with tempfile.TemporaryDirectory() as base:
            out = os.path.join(base, "ejected")
            runner = CliRunner()
            result = runner.invoke(
                eject_cmd, ["--output", out, "--tests-dir", "/no/such/dir"]
            )
            self.assertNotEqual(result.exit_code, 0)


class TestEjectDoesNotShipCherenkovsOwnFixtures(unittest.TestCase):
    """The severe defect from the 2026-08-12 real-user walkthrough.

    `cherenkov generate` wrote the user's tests to ./stub/generated_tests (cwd),
    but eject resolved the same default against the *installed package*. Driving
    the documented generate -> eject flow therefore produced 17 files that were
    CHERENKOV's own fixtures — including the deliberately sabotaged
    demo_weakened / demo_deleted / demo_hallucinated specs — with the user's own
    tests absent, under a "100% standard, runs standalone" banner and exit 0.

    For a product whose thesis is catching weakened tests, shipping its own
    weakened fixtures into a user's repo and calling it success is the worst
    available failure. These pin the flow shut.
    """

    SABOTAGED = ("demo_weakened", "demo_deleted", "demo_hallucinated", "golden_weakened")

    def test_default_eject_ships_the_users_own_tests(self):
        """generate -> eject with no flags: the user's filenames must come out."""
        from cherenkov.execution.eject import EjectorEngine

        with tempfile.TemporaryDirectory() as cwd, tempfile.TemporaryDirectory() as base:
            # Stand in for `cherenkov generate --spec api.yaml` run from `cwd`,
            # which writes to the relative default "stub/generated_tests".
            gen_dir = os.path.join(cwd, "stub", "generated_tests")
            os.makedirs(gen_dir)
            with open(os.path.join(gen_dir, "orders_flow.spec.ts"), "w") as f:
                f.write("import { test, expect } from '@playwright/test';\n")

            prev = os.getcwd()
            os.chdir(cwd)
            try:
                out = os.path.join(base, "ejected")
                self.assertTrue(EjectorEngine(run_id="test-run").eject_suite(out))
            finally:
                os.chdir(prev)

            ejected = os.listdir(os.path.join(out, "tests"))
            self.assertIn("orders_flow.spec.ts", ejected, f"user's test missing; got {ejected}")
            for name in self.SABOTAGED:
                self.assertFalse(
                    any(name in f for f in ejected),
                    f"ejected suite contains CHERENKOV's sabotaged fixture {name}: {ejected}",
                )

    def test_eject_refuses_rather_than_shipping_package_fixtures(self):
        """From a cwd with no generated tests, eject must fail — not fall back.

        Exit-code behaviour matters as much as the files: the CLI prints
        "ejected successfully ... 100% standard and runs standalone" on a True
        return, so returning True here is what made the defect dangerous.
        """
        from cherenkov.execution.eject import EjectorEngine

        with tempfile.TemporaryDirectory() as cwd, tempfile.TemporaryDirectory() as base:
            prev = os.getcwd()
            os.chdir(cwd)
            try:
                out = os.path.join(base, "ejected")
                self.assertFalse(
                    EjectorEngine(run_id="test-run").eject_suite(out),
                    "eject reported success with no user tests to eject",
                )
            finally:
                os.chdir(prev)

    def test_eject_refuses_a_tests_dir_inside_the_package(self):
        """Even when pointed at them explicitly, package fixtures are refused."""
        from cherenkov.execution.eject import EjectorEngine

        engine = EjectorEngine(run_id="test-run")
        with tempfile.TemporaryDirectory() as base:
            out = os.path.join(base, "ejected")
            engine.tests_src_dir = engine.fixtures_dir  # inside the package
            self.assertFalse(engine.eject_suite(out))

    def test_cli_default_eject_exits_nonzero_instead_of_claiming_success(self):
        """End-to-end through the CLI, which is where the banner is printed."""
        from click.testing import CliRunner

        from cherenkov.cli.commands.simple import eject_cmd

        with tempfile.TemporaryDirectory() as cwd, tempfile.TemporaryDirectory() as base:
            prev = os.getcwd()
            os.chdir(cwd)
            try:
                out = os.path.join(base, "ejected")
                result = CliRunner().invoke(eject_cmd, ["--output", out])
            finally:
                os.chdir(prev)

            self.assertNotEqual(result.exit_code, 0, result.output)
            self.assertNotIn("runs standalone", result.output)
