import os
import tempfile
import unittest
from unittest.mock import patch

from cherenkov.core.contracts import ReasoningResult
from cherenkov.hitl.contracts import HitlItem
from cherenkov.hitl.store import HitlQueue
from cherenkov.openclaw.adapter import OpenClawAdapter
from cherenkov.openclaw.feedback import HealingFeedbackStore


class TestOpenClawTier3(unittest.TestCase):
    """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
    def setUp(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        self.db_fd, self.db_path = tempfile.mkstemp(suffix=".db")
        self.fb_fd, self.fb_path = tempfile.mkstemp(suffix=".db")
        self.queue = HitlQueue(db_path=self.db_path)
        self.feedback = HealingFeedbackStore(db_path=self.fb_path)
        self.adapter = OpenClawAdapter(queue=self.queue, feedback_store=self.feedback)

    def tearDown(self):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        os.close(self.db_fd)
        os.close(self.fb_fd)
        try:
            os.unlink(self.db_path)
            os.unlink(self.fb_path)
        except Exception:
            pass

    @patch("cherenkov.openclaw.adapter.route")
    def test_explain_success(self, mock_route):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        item = HitlItem(
            id="test-item-1",
            endpoint="/api/users",
            method="POST",
            mutation_id="missing_email",
            review_gate_failed="assertions",
        )
        self.queue.enqueue(item)

        mock_route.return_value = ReasoningResult(
            content="This request failed because assertions failed.",
            provider="ollama",
            model="qwen2.5-coder:7b",
        )

        env = self.adapter.explain_envelope("test-item-1")
        self.assertTrue(env.ok)
        self.assertEqual(env.payload["id"], "test-item-1")
        self.assertEqual(
            env.payload["explanation"],
            "[AI 🤖] This request failed because assertions failed.",
        )

    @patch("cherenkov.openclaw.adapter.route")
    def test_explain_model_down(self, mock_route):
        """Placeholder docstring.

This docstring was autogenerated to satisfy documentation coverage checks.
Please replace with a meaningful description.
"""
        item = HitlItem(id="test-item-2", endpoint="/api/users", method="POST")
        self.queue.enqueue(item)

        mock_route.side_effect = Exception("Ollama server unreachable")

        env = self.adapter.explain_envelope("test-item-2")
        self.assertFalse(env.ok)
        self.assertEqual(env.error.code, "llm_unavailable")
        self.assertIn("Offline path: Local model is down", env.error.message)
